//! Metadata extracted from the SDK 238-R3.4.8 catalog for the implemented slice.
//! Imported rule messages retain their recorded LGPL-3.0 terms.
//! See THIRD_PARTY_NOTICES.md and the business-rules fixture NOTICE.md.
//! The catalog regression test detects drift in source, site, message or severity.
use super::{Severity, Source, identity::IdentityCheck, rules::Check};

pub(super) struct Rule {
    pub source: Source,
    pub site: &'static str,
    pub code: &'static str,
    pub message: &'static str,
    pub severity: Severity,
    pub check: Check,
}

use super::{
    structural::{Context as C, Requirement as R},
    xml::{a, b},
};

use super::code_lists::CodeListCheck;

use super::totals::TotalsCheck;

use super::ksa_fields::KsaFieldCheck;

use super::ksa_buyer::KsaBuyerCheck;

use super::ksa_common::KsaCommonCheck;

use super::vat::VatCheck;

use super::ksa_adjustments::KsaAdjustmentCheck;

use super::ksa_exemptions::KsaExemptionCheck;

pub(super) const RULES: &[Rule] = &[
    Rule {
        source: Source::Cen,
        site: "cen:001:BR-52",
        code: "BR-52",
        severity: Severity::Warning,
        message: "[BR-52]-Each Additional supporting document (BG-24) shall contain a Supporting document reference (BT-122).",
        check: Check::Structural(
            C::All(&[a("AdditionalDocumentReference")]),
            R::Nonempty(&[b("ID")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:002:BR-31",
        code: "BR-31",
        severity: Severity::Error,
        message: "[BR-31]-Each Document level allowance (BG-20) shall have a Document level allowance amount (BT-92).",
        check: Check::Structural(C::DocumentAllowance(false), R::Exists(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:003:BR-32",
        code: "BR-32",
        severity: Severity::Error,
        message: "[BR-32]-Each Document level allowance (BG-20) shall have a Document level allowance VAT category code (BT-95).",
        check: Check::Structural(
            C::DocumentAllowance(false),
            R::VatCategory(&[a("TaxCategory")], true),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:004:BR-DEC-01",
        code: "BR-DEC-01",
        severity: Severity::Warning,
        message: "[BR-DEC-01]-The allowed maximum number of decimals for the Document level allowance amount (BT-92) is 2.",
        check: Check::Structural(C::DocumentAllowance(false), R::Scale(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:005:BR-DEC-02",
        code: "BR-DEC-02",
        severity: Severity::Warning,
        message: "[BR-DEC-02]-The allowed maximum number of decimals for the Document level allowance base amount (BT-93) is 2.",
        check: Check::Structural(C::DocumentAllowance(false), R::Scale(&[b("BaseAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:006:BR-36",
        code: "BR-36",
        severity: Severity::Warning,
        message: "[BR-36]-Each Document level charge (BG-21) shall have a Document level charge amount (BT-99).",
        check: Check::Structural(C::DocumentAllowance(true), R::Exists(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:007:BR-37",
        code: "BR-37",
        severity: Severity::Warning,
        message: "[BR-37]-Each Document level charge (BG-21) shall have a Document level charge VAT category code (BT-102).",
        check: Check::Structural(
            C::DocumentAllowance(true),
            R::Exists(&[a("TaxCategory"), b("ID")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:008:BR-DEC-06",
        code: "BR-DEC-06",
        severity: Severity::Warning,
        message: "[BR-DEC-06]-The allowed maximum number of decimals for the Document level charge base amount (BT-100) is 2.",
        check: Check::Structural(C::DocumentAllowance(true), R::Scale(&[b("BaseAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:009:BR-DEC-05",
        code: "BR-DEC-05",
        severity: Severity::Warning,
        message: "[BR-DEC-05]-The allowed maximum number of decimals for the Document level charge amount (BT-99) is 2.",
        check: Check::Structural(C::DocumentAllowance(true), R::Scale(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:010:BR-43",
        code: "BR-43",
        severity: Severity::Warning,
        message: "[BR-43]-Each Invoice line charge (BG-28) shall have an Invoice line charge amount (BT-141).",
        check: Check::Structural(C::LineCharge, R::Exists(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:011:BR-DEC-27",
        code: "BR-DEC-27",
        severity: Severity::Warning,
        message: "[BR-DEC-27]-The allowed maximum number of decimals for the Invoice line charge amount (BT-141) is 2.",
        check: Check::Structural(C::LineCharge, R::Scale(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:012:BR-DEC-28",
        code: "BR-DEC-28",
        severity: Severity::Warning,
        message: "[BR-DEC-28]-The allowed maximum number of decimals for the Invoice line charge base amount (BT-142) is 2.",
        check: Check::Structural(C::LineCharge, R::Scale(&[b("BaseAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:013:BR-13",
        code: "BR-13",
        severity: Severity::Warning,
        message: "[BR-13]-An Invoice shall have the Invoice total amount without VAT (BT-109).",
        check: Check::Structural(
            C::All(&[a("LegalMonetaryTotal")]),
            R::Exists(&[b("TaxExclusiveAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:014:BR-14",
        code: "BR-14",
        severity: Severity::Error,
        message: "[BR-14]-An Invoice shall have the Invoice total amount with VAT (BT-112).",
        check: Check::Structural(
            C::All(&[a("LegalMonetaryTotal")]),
            R::Exists(&[b("TaxInclusiveAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:015:BR-15",
        code: "BR-15",
        severity: Severity::Error,
        message: "[BR-15]-An Invoice shall have the Amount due for payment (BT-115).",
        check: Check::Structural(
            C::All(&[a("LegalMonetaryTotal")]),
            R::Exists(&[b("PayableAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:016:BR-CO-10",
        code: "BR-CO-10",
        severity: Severity::Warning,
        message: "[BR-CO-10]-Sum of Invoice line net amount (BT-106) = Σ Invoice line net amount (BT-131).",
        check: Check::LineSum,
    },
    Rule {
        source: Source::Cen,
        site: "cen:017:BR-CO-11",
        code: "BR-CO-11",
        severity: Severity::Error,
        message: "[BR-CO-11]-Sum of allowances on document level (BT-107) = Σ Document level allowance amount (BT-92).",
        check: Check::Totals(TotalsCheck::AllowanceSum),
    },
    Rule {
        source: Source::Cen,
        site: "cen:018:BR-CO-12",
        code: "BR-CO-12",
        severity: Severity::Error,
        message: "[BR-CO-12]-Sum of charges on document level (BT-108) = Σ Document level charge amount (BT-99).",
        check: Check::Totals(TotalsCheck::EmptyChargeSum),
    },
    Rule {
        source: Source::Cen,
        site: "cen:019:BR-CO-12",
        code: "BR-CO-12",
        severity: Severity::Error,
        message: "[BR-CO-12]-Sum of charges on document level (BT-108) = Σ Document level charge amount (BT-99).",
        check: Check::Totals(TotalsCheck::ChargeSum),
    },
    Rule {
        source: Source::Cen,
        site: "cen:020:BR-CO-13",
        code: "BR-CO-13",
        severity: Severity::Warning,
        message: "[BR-CO-13]-Invoice total amount without VAT (BT-109) = Σ Invoice line net amount (BT-131) - Sum of allowances on document level (BT-107) + Sum of charges on document level (BT-108).",
        check: Check::Totals(TotalsCheck::EmptyChargeExclusive),
    },
    Rule {
        source: Source::Cen,
        site: "cen:021:BR-CO-13",
        code: "BR-CO-13",
        severity: Severity::Warning,
        message: "[BR-CO-13]-Invoice total amount without VAT (BT-109) = Σ Invoice line net amount (BT-131) - Sum of allowances on document level (BT-107) + Sum of charges on document level (BT-108).",
        check: Check::Totals(TotalsCheck::Exclusive),
    },
    Rule {
        source: Source::Cen,
        site: "cen:022:BR-CO-16",
        code: "BR-CO-16",
        severity: Severity::Warning,
        message: "[BR-CO-16]-Amount due for payment (BT-115) = Invoice total amount with VAT (BT-112) -Pre-Paid amount (BT-113) + Rounding amount (BT-114).",
        check: Check::Totals(TotalsCheck::Payable),
    },
    Rule {
        source: Source::Cen,
        site: "cen:023:BR-DEC-09",
        code: "BR-DEC-09",
        severity: Severity::Warning,
        message: "[BR-DEC-09]-The allowed maximum number of decimals for the Sum of Invoice line net amount (BT-106) is 2.",
        check: Check::TotalScale("LineExtensionAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:024:BR-DEC-10",
        code: "BR-DEC-10",
        severity: Severity::Warning,
        message: "[BR-DEC-10]-The allowed maximum number of decimals for the Sum of allowanced on document level (BT-107) is 2.",
        check: Check::TotalScale("AllowanceTotalAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:025:BR-DEC-11",
        code: "BR-DEC-11",
        severity: Severity::Warning,
        message: "[BR-DEC-11]-The allowed maximum number of decimals for the Sum of charges on document level (BT-108) is 2.",
        check: Check::TotalScale("ChargeTotalAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:026:BR-DEC-12",
        code: "BR-DEC-12",
        severity: Severity::Warning,
        message: "[BR-DEC-12]-The allowed maximum number of decimals for the Invoice total amount without VAT (BT-109) is 2.",
        check: Check::TotalScale("TaxExclusiveAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:027:BR-DEC-14",
        code: "BR-DEC-14",
        severity: Severity::Warning,
        message: "[BR-DEC-14]-The allowed maximum number of decimals for the Invoice total amount with VAT (BT-112) is 2.",
        check: Check::TotalScale("TaxInclusiveAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:028:BR-DEC-16",
        code: "BR-DEC-16",
        severity: Severity::Warning,
        message: "[BR-DEC-16]-The allowed maximum number of decimals for the Pre-Paid amount (BT-113) is 2.",
        check: Check::TotalScale("PrepaidAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:029:BR-DEC-17",
        code: "BR-DEC-17",
        severity: Severity::Warning,
        message: "[BR-DEC-17]-The allowed maximum number of decimals for the Rounding amount (BT-114) is 2.",
        check: Check::TotalScale("PayableRoundingAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:030:BR-DEC-18",
        code: "BR-DEC-18",
        severity: Severity::Warning,
        message: "[BR-DEC-18]-The allowed maximum number of decimals for the Amount due for payment (BT-115) is 2.  ",
        check: Check::TotalScale("PayableAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:031:BR-02",
        code: "BR-02",
        severity: Severity::Warning,
        message: "[BR-02]-An Invoice shall have an Invoice number (BT-1).",
        check: Check::Structural(C::Root, R::Nonempty(&[b("ID")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:032:BR-KSA-F-06-C1",
        code: "BR-KSA-F-06-C1",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C1] - Field character limits for Invoice number field (BT-1) have not been met. The minimum limit is 1 character and the maximum limit is 127 characters.",
        check: Check::Structural(C::Root, R::Length(&[b("ID")], 0, 127)),
    },
    Rule {
        source: Source::Cen,
        site: "cen:033:BR-KSA-F-06-C2",
        code: "BR-KSA-F-06-C2",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C2] - Field character limits for Invoice note field (BT-22) have not been met. The maximum limit is 1000 characters.",
        check: Check::Structural(C::Root, R::InvoiceNote),
    },
    Rule {
        source: Source::Cen,
        site: "cen:034:BR-03",
        code: "BR-03",
        severity: Severity::Error,
        message: "[BR-03]-An Invoice shall have an Invoice issue date (BT-2).",
        check: Check::Structural(C::Root, R::Nonempty(&[b("IssueDate")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:035:BR-04",
        code: "BR-04",
        severity: Severity::Error,
        message: "[BR-04]-An Invoice shall have an Invoice type code (BT-3).",
        check: Check::Structural(C::Root, R::InvoiceType),
    },
    Rule {
        source: Source::Cen,
        site: "cen:036:BR-05",
        code: "BR-05",
        severity: Severity::Error,
        message: "[BR-05]-An Invoice shall have an Invoice currency code (BT-5).",
        check: Check::Structural(C::Root, R::Nonempty(&[b("DocumentCurrencyCode")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:037:BR-06",
        code: "BR-06",
        severity: Severity::Warning,
        message: "[BR-06]-An Invoice shall contain the Seller name (BT-27).",
        check: Check::Structural(
            C::Root,
            R::Nonempty(&[
                a("AccountingSupplierParty"),
                a("Party"),
                a("PartyLegalEntity"),
                b("RegistrationName"),
            ]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:038:BR-KSA-F-06-C10",
        code: "BR-KSA-F-06-C10",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C10] - Field character limits for Seller name field (BT-27) have not been met. The minimum limit is 1 character and the maximum limit is 1000 characters.\n                        ",
        check: Check::Structural(
            C::Root,
            R::Length(
                &[
                    a("AccountingSupplierParty"),
                    a("Party"),
                    a("PartyLegalEntity"),
                    b("RegistrationName"),
                ],
                1,
                1000,
            ),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:039:BR-KSA-F-06-C8",
        code: "BR-KSA-F-06-C8",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C8] - Field character limits for the Seller Address - Province/State field (BT-39) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::Structural(
            C::Root,
            R::Length(
                &[
                    a("AccountingSupplierParty"),
                    a("Party"),
                    a("PostalAddress"),
                    b("CountrySubentity"),
                ],
                0,
                127,
            ),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:040:BR-08",
        code: "BR-08",
        severity: Severity::Warning,
        message: "[BR-08]-An Invoice shall contain the Seller postal address (BG-5) ",
        check: Check::Structural(
            C::Root,
            R::Exists(&[a("AccountingSupplierParty"), a("Party"), a("PostalAddress")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:041:BR-KSA-F-06-C27",
        code: "BR-KSA-F-06-C27",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C27] - Field character limits for the Buyer Address - Province/State field (BT-54) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::Structural(
            C::Root,
            R::Length(
                &[
                    a("AccountingCustomerParty"),
                    a("Party"),
                    a("PostalAddress"),
                    b("CountrySubentity"),
                ],
                0,
                127,
            ),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:042:BR-16",
        code: "BR-16",
        severity: Severity::Error,
        message: "[BR-16]-An Invoice shall have at least one Invoice line (BG-25)",
        check: Check::Structural(C::Root, R::InvoiceLines),
    },
    Rule {
        source: Source::Cen,
        site: "cen:043:BR-53",
        code: "BR-53",
        severity: Severity::Warning,
        message: "[BR-53]-If the VAT accounting currency code (BT-6) is present, then the Invoice total VAT amount in accounting currency (BT-111) shall be provided.",
        check: Check::Structural(C::Root, R::TaxAccounting),
    },
    Rule {
        source: Source::Cen,
        site: "cen:044:BR-KSA-F-06-C17",
        code: "BR-KSA-F-06-C17",
        severity: Severity::Error,
        message: "[BR-KSA-F-06-C17] - Field character limits for Invoice line identifier field (BT-126) have not been met. The minimum limit is 1 character and the maximum limit is 6 characters.",
        check: Check::Structural(C::All(&[a("InvoiceLine")]), R::Length(&[b("ID")], 1, 6)),
    },
    Rule {
        source: Source::Cen,
        site: "cen:045:BR-KSA-F-06-C30",
        code: "BR-KSA-F-06-C30",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C30] - Field character limits for Item Buyer's identifier field (BT-156) have not been met. The maximum limit is 127 characters.",
        check: Check::Structural(
            C::All(&[a("InvoiceLine")]),
            R::Length(&[a("Item"), a("BuyersItemIdentification"), b("ID")], 0, 127),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:046:BR-KSA-F-06-C31",
        code: "BR-KSA-F-06-C31",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C31] - Field character limits for Item Seller's identifier field (BT-155) have not been met. The maximum limit is 127 characters.",
        check: Check::Structural(
            C::All(&[a("InvoiceLine")]),
            R::Length(
                &[a("Item"), a("SellersItemIdentification"), b("ID")],
                0,
                127,
            ),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:047:BR-KSA-F-06-C20",
        code: "BR-KSA-F-06-C20",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C20] - Field character limits for Item standard identifier field (BT-157) have not been met. The maximum limit is 127 characters.",
        check: Check::Structural(
            C::All(&[a("InvoiceLine")]),
            R::Length(
                &[a("Item"), a("StandardItemIdentification"), b("ID")],
                0,
                127,
            ),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:048:BR-CO-15",
        code: "BR-CO-15",
        severity: Severity::Error,
        message: "[BR-CO-15]-Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).",
        check: Check::InclusiveTotal,
    },
    Rule {
        source: Source::Cen,
        site: "cen:049:BR-CO-18",
        code: "BR-CO-18",
        severity: Severity::Error,
        message: "[BR-CO-18]-An Invoice shall at least have one VAT breakdown group (BG-23).",
        check: Check::Structural(C::Root, R::Exists(&[a("TaxTotal"), a("TaxSubtotal")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:050:BR-E-01",
        code: "BR-E-01",
        severity: Severity::Warning,
        message: "[BR-E-01]-An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151 or BT-95 or BT-102) is \"Exempt from VAT\" shall contain at least one VAT breakdown (BG-23) with the VAT category code (BT-118) equal to \"Exempt from VAT\".",
        check: Check::Vat(VatCheck::ExemptBreakdown),
    },
    Rule {
        source: Source::Cen,
        site: "cen:051:BR-O-01",
        code: "BR-O-01",
        severity: Severity::Warning,
        message: "[BR-O-01]-An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151 or BT-95 or BT-102) is \"Not subject to VAT\" shall contain exactly at least one VAT breakdown group (BG-23) with the VAT category code (BT-118) equal to \"Not subject to VAT\".",
        check: Check::Vat(VatCheck::OutsideBreakdown),
    },
    Rule {
        source: Source::Cen,
        site: "cen:052:BR-S-01",
        code: "BR-S-01",
        severity: Severity::Warning,
        message: "[BR-S-01]-An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-102) is \"Standard rated\" shall contain in the VAT breakdown (BG-23) at least one VAT category code (BT-118) equal with \"Standard rated\".",
        check: Check::Vat(VatCheck::StandardBreakdown),
    },
    Rule {
        source: Source::Cen,
        site: "cen:053:BR-Z-07",
        code: "BR-Z-07",
        severity: Severity::Error,
        message: "[BR-Z-07]-In a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is \"Zero rated\" the Document level charge VAT rate (BT-103) shall be 0 (zero).",
        check: Check::Vat(VatCheck::ZeroChargeRate),
    },
    Rule {
        source: Source::Cen,
        site: "cen:054:BR-E-07",
        code: "BR-E-07",
        severity: Severity::Error,
        message: "[BR-E-07]-In a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is \"Exempt from VAT\", the Document level charge VAT rate (BT-103) shall be 0 (zero).",
        check: Check::Vat(VatCheck::ExemptChargeRate),
    },
    Rule {
        source: Source::Cen,
        site: "cen:055:BR-Z-01",
        code: "BR-Z-01",
        severity: Severity::Warning,
        message: "[BR-Z-01]-An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or a Document level charge (BG-21) where the VAT category code (BT-151 or BT-95 or BT-102) is \"Zero rated\" shall contain in the VAT breakdown (BG-23) at least one VAT category code (BT-118) equal with \"Zero rated\".",
        check: Check::Vat(VatCheck::ZeroBreakdown),
    },
    Rule {
        source: Source::Cen,
        site: "cen:056:BR-KSA-F-06-C18",
        code: "BR-KSA-F-06-C18",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C18] - Field character limits for Invoiced quantity unit of measure field (BT-130) have not been met. The maximum limit is 127 characters.",
        check: Check::Structural(
            C::Lines,
            R::AttributeLength(&[b("InvoicedQuantity")], "unitCode", 127),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:057:BR-KSA-F-06-C19",
        code: "BR-KSA-F-06-C19",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C19] - Field character limits for Item name field (BT-153) have not been met. The minimum limit is 3 character and the maximum limit is 1000 characters.",
        check: Check::Structural(C::Lines, R::Length(&[a("Item"), b("Name")], 3, 1000)),
    },
    Rule {
        source: Source::Cen,
        site: "cen:058:BR-KSA-F-C-01",
        code: "BR-KSA-F-C-01",
        severity: Severity::Warning,
        message: "[BR-KSA-F-C-01] - Please recheck Item Description (BT-153). Providing unclear description violates the requirements specified in Article 53 of VAT Regulations.",
        check: Check::Structural(C::Lines, R::ItemName),
    },
    Rule {
        source: Source::Cen,
        site: "cen:059:BR-21",
        code: "BR-21",
        severity: Severity::Warning,
        message: "[BR-21]-Each Invoice line (BG-25) shall have an Invoice line identifier (BT-126).",
        check: Check::Structural(C::Lines, R::Nonempty(&[b("ID")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:060:BR-22",
        code: "BR-22",
        severity: Severity::Error,
        message: "[BR-22]-Each Invoice line (BG-25) shall have an Invoiced quantity (BT-129).",
        check: Check::Structural(C::Lines, R::InvoicedQuantity),
    },
    Rule {
        source: Source::Cen,
        site: "cen:061:BR-24",
        code: "BR-24",
        severity: Severity::Error,
        message: "[BR-24]-Each Invoice line (BG-25) shall have an Invoice line net amount (BT-131).",
        check: Check::Structural(C::Lines, R::Exists(&[b("LineExtensionAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:062:BR-25",
        code: "BR-25",
        severity: Severity::Warning,
        message: "[BR-25]-Each Invoice line (BG-25) shall contain the Item name (BT-153).",
        check: Check::ItemName,
    },
    Rule {
        source: Source::Cen,
        site: "cen:063:BR-26",
        code: "BR-26",
        severity: Severity::Error,
        message: "[BR-26]-Each Invoice line (BG-25) shall contain the Item net price (BT-146).",
        check: Check::Structural(C::Lines, R::Exists(&[a("Price"), b("PriceAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:064:BR-CO-04",
        code: "BR-CO-04",
        severity: Severity::Error,
        message: "[BR-CO-04]-Each Invoice line (BG-25) shall be categorized with an Invoiced item VAT category code (BT-151).",
        check: Check::Structural(C::Lines, R::ItemVatCategory),
    },
    Rule {
        source: Source::Cen,
        site: "cen:065:BR-DEC-23",
        code: "BR-DEC-23",
        severity: Severity::Warning,
        message: "[BR-DEC-23]-The allowed maximum number of decimals for the Invoice line net amount (BT-131) is 2.",
        check: Check::Structural(C::Lines, R::Scale(&[b("LineExtensionAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:066:BR-41",
        code: "BR-41",
        severity: Severity::Error,
        message: "[BR-41]-Each Invoice line allowance (BG-27) shall have an Invoice line allowance amount (BT-136).",
        check: Check::Structural(C::LineAllowance, R::Exists(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:067:BR-DEC-24",
        code: "BR-DEC-24",
        severity: Severity::Warning,
        message: "[BR-DEC-24]-The allowed maximum number of decimals for the Invoice line allowance amount (BT-136) is 2.",
        check: Check::LineAllowanceScale("Amount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:068:BR-DEC-25",
        code: "BR-DEC-25",
        severity: Severity::Warning,
        message: "[BR-DEC-25]-The allowed maximum number of decimals for the Invoice line allowance base amount (BT-137) is 2.",
        check: Check::LineAllowanceScale("BaseAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:069:BR-54",
        code: "BR-54",
        severity: Severity::Error,
        message: "[BR-54]-Each Item attribute (BG-32) shall contain an Item attribute name (BT-160) and an Item attribute value (BT-161).",
        check: Check::Structural(C::All(&[a("AdditionalItemProperty")]), R::ItemProperty),
    },
    Rule {
        source: Source::Cen,
        site: "cen:070:BR-49",
        code: "BR-49",
        severity: Severity::Warning,
        message: "[BR-49]-A Payment instruction (BG-16) shall specify the Payment means type code (BT-81).",
        check: Check::Structural(C::All(&[a("PaymentMeans")]), R::PaymentCode),
    },
    Rule {
        source: Source::Cen,
        site: "cen:071:BR-55",
        code: "BR-55",
        severity: Severity::Error,
        message: "[BR-55]-Each Preceding Invoice reference (BG-3) shall contain a Preceding Invoice reference (BT-25).",
        check: Check::Structural(
            C::All(&[a("BillingReference")]),
            R::Nonempty(&[a("InvoiceDocumentReference"), b("ID")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:072:BR-09",
        code: "BR-09",
        severity: Severity::Warning,
        message: "[BR-09]-The Seller postal address (BG-5) shall contain a Seller country code (BT-40).",
        check: Check::Structural(
            C::All(&[a("AccountingSupplierParty"), a("Party"), a("PostalAddress")]),
            R::Nonempty(&[a("Country"), b("IdentificationCode")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:073:BR-CO-14",
        code: "BR-CO-14",
        severity: Severity::Error,
        message: "[BR-CO-14]-Invoice total VAT amount (BT-110) = Σ VAT category tax amount (BT-117).",
        check: Check::TaxSum,
    },
    Rule {
        source: Source::Cen,
        site: "cen:074:BR-45",
        code: "BR-45",
        severity: Severity::Error,
        message: "[BR-45]-Each VAT breakdown (BG-23) shall have a VAT category taxable amount (BT-116).",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::Exists(&[b("TaxableAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:075:BR-46",
        code: "BR-46",
        severity: Severity::Error,
        message: "[BR-46]-Each VAT breakdown (BG-23) shall have a VAT category tax amount (BT-117).",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::Exists(&[b("TaxAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:076:BR-47",
        code: "BR-47",
        severity: Severity::Error,
        message: "[BR-47]-Each VAT breakdown (BG-23) shall be defined through a VAT category code (BT-118).",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::VatCategory(&[a("TaxCategory")], false),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:077:BR-48",
        code: "BR-48",
        severity: Severity::Error,
        message: "[BR-48]-Each VAT breakdown (BG-23) shall have a VAT category rate (BT-119), except if the Invoice is not subject to VAT.",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::VatRate,
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:078:BR-CO-17",
        code: "BR-CO-17",
        severity: Severity::Warning,
        message: "[BR-CO-17]-VAT category tax amount (BT-117) = VAT category taxable amount (BT-116) x (VAT category rate (BT-119) / 100), rounded to two decimals.",
        check: Check::Vat(VatCheck::TaxComputation),
    },
    Rule {
        source: Source::Cen,
        site: "cen:079:BR-DEC-19",
        code: "BR-DEC-19",
        severity: Severity::Warning,
        message: "[BR-DEC-19]-The allowed maximum number of decimals for the VAT category taxable amount (BT-116) is 2.",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::Scale(&[b("TaxableAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:080:BR-DEC-20",
        code: "BR-DEC-20",
        severity: Severity::Warning,
        message: "[BR-DEC-20]-The allowed maximum number of decimals for the VAT category tax amount (BT-117) is 2.",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::Scale(&[b("TaxAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:081:BR-E-08",
        code: "BR-E-08",
        severity: Severity::Warning,
        message: "[BR-E-08]-In a VAT breakdown (BG-23) where the VAT category code (BT-118) is \" Exempt from VAT\" the VAT category taxable amount (BT-116) shall equal the sum of Invoice line net amounts (BT-131) minus the sum of Document level allowance amounts (BT-92) plus the sum of Document level charge amounts (BT-99) where the VAT category codes (BT-151, BT-95, BT-102) are \"Exempt from VAT\".",
        check: Check::Vat(VatCheck::ExemptTaxable),
    },
    Rule {
        source: Source::Cen,
        site: "cen:082:BR-E-09",
        code: "BR-E-09",
        severity: Severity::Error,
        message: "[BR-E-09]-The VAT category tax amount (BT-117) In a VAT breakdown (BG-23) where the VAT category code (BT-118) equals \"Exempt from VAT\" shall equal 0 (zero).",
        check: Check::Vat(VatCheck::ExemptTaxZero),
    },
    Rule {
        source: Source::Cen,
        site: "cen:083:BR-E-06",
        code: "BR-E-06",
        severity: Severity::Error,
        message: "[BR-E-06]-In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is \"Exempt from VAT\", the Document level allowance VAT rate (BT-96) shall be 0 (zero).",
        check: Check::Vat(VatCheck::ExemptAllowanceRate),
    },
    Rule {
        source: Source::Cen,
        site: "cen:084:BR-E-05",
        code: "BR-E-05",
        severity: Severity::Error,
        message: "[BR-E-05]-In an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is \"Exempt from VAT\", the Invoiced item VAT rate (BT-152) shall be 0 (zero).",
        check: Check::Vat(VatCheck::ExemptItemRate),
    },
    Rule {
        source: Source::Cen,
        site: "cen:085:BR-O-08",
        code: "BR-O-08",
        severity: Severity::Warning,
        message: "[BR-O-08]-In a VAT breakdown (BG-23) where the VAT category code (BT-118) is \" Not subject to VAT\" the VAT category taxable amount (BT-116) shall equal the sum of Invoice line net amounts (BT-131) minus the sum of Document level allowance amounts (BT-92) plus the sum of Document level charge amounts (BT-99) where the VAT category codes (BT-151, BT-95, BT-102) are \"Not subject to VAT\".",
        check: Check::Vat(VatCheck::OutsideTaxable),
    },
    Rule {
        source: Source::Cen,
        site: "cen:086:BR-O-09",
        code: "BR-O-09",
        severity: Severity::Error,
        message: "[BR-O-09]-The VAT category tax amount (BT-117) in a VAT breakdown (BG-23) where the VAT category code (BT-118) is \"Not subject to VAT\" shall be 0 (zero).",
        check: Check::Vat(VatCheck::OutsideTaxZero),
    },
    Rule {
        source: Source::Cen,
        site: "cen:087:BR-S-08",
        code: "BR-S-08",
        severity: Severity::Warning,
        message: "[BR-S-08]-In a VAT breakdown (BG-23) where the VAT category code (BT-118) is \" Standard rated\" the VAT category taxable amount (BT-116) shall equal the sum of Invoice line net amounts (BT-131) minus the sum of Document level allowance amounts (BT-92) plus the sum of Document level charge amounts (BT-99) where the VAT category codes (BT-151, BT-95, BT-102) are \"Standard Rate\".",
        check: Check::Vat(VatCheck::StandardTaxable),
    },
    Rule {
        source: Source::Cen,
        site: "cen:088:BR-S-09",
        code: "BR-S-09",
        severity: Severity::Warning,
        message: "[BR-S-09]-The VAT category tax amount (BT-117) in a VAT breakdown (BG-23) where VAT category code (BT-118) is \"Standard rated\" shall equal the VAT category taxable amount (BT-116) multiplied by the VAT category rate (BT-119) / 100), rounded to two decimals.",
        check: Check::Vat(VatCheck::StandardTaxComputation),
    },
    Rule {
        source: Source::Cen,
        site: "cen:089:BR-S-10",
        code: "BR-S-10",
        severity: Severity::Warning,
        message: "[BR-S-10]-A VAT breakdown (BG-23) with VAT Category code (BT-118) \"Standard rate\" shall not have a VAT exemption reason code (BT-121) or VAT exemption reason text (BT-120).",
        check: Check::Vat(VatCheck::StandardNoExemption),
    },
    Rule {
        source: Source::Cen,
        site: "cen:090:BR-S-06",
        code: "BR-S-06",
        severity: Severity::Error,
        message: "[BR-S-06]-In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is \"Standard rated\" the Document level allowance VAT rate (BT-96) shall be greater than zero.",
        check: Check::Vat(VatCheck::StandardAllowanceRate),
    },
    Rule {
        source: Source::Cen,
        site: "cen:091:BR-S-07",
        code: "BR-S-07",
        severity: Severity::Warning,
        message: "[BR-S-07]--In a Document level charge (BG-21) where the Document level charge VAT category code (BT-102) is \"Standard rated\" the Document level charge VAT rate (BT-103) shall be greater than zero.",
        check: Check::Vat(VatCheck::StandardChargeRate),
    },
    Rule {
        source: Source::Cen,
        site: "cen:092:BR-Z-08",
        code: "BR-Z-08",
        severity: Severity::Warning,
        message: "[BR-Z-08]-In a VAT breakdown (BG-23) where the VAT category code (BT-118) is \" Zero rated\" the VAT category taxable amount (BT-116) shall equal the sum of Invoice line net amounts (BT-131) minus the sum of Document level allowance amounts (BT-92) plus the sum of Document level charge amounts (BT-99) where the VAT category codes (BT-151, BT-95, BT-102) are \"Zero Rated\".",
        check: Check::Vat(VatCheck::ZeroTaxable),
    },
    Rule {
        source: Source::Cen,
        site: "cen:093:BR-Z-09",
        code: "BR-Z-09",
        severity: Severity::Error,
        message: "[BR-Z-09]-The VAT category tax amount (BT-117) in a VAT breakdown (BG-23) where VAT category code (BT-118) is \"Zero rated\" shall equal 0 (zero).",
        check: Check::Vat(VatCheck::ZeroTaxZero),
    },
    Rule {
        source: Source::Cen,
        site: "cen:094:BR-Z-06",
        code: "BR-Z-06",
        severity: Severity::Error,
        message: "[BR-Z-06]-In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is \"Zero rated\" the Document level allowance VAT rate (BT-96) shall be 0 (zero).",
        check: Check::Vat(VatCheck::ZeroAllowanceRate),
    },
    Rule {
        source: Source::Cen,
        site: "cen:095:BR-Z-05",
        code: "BR-Z-05",
        severity: Severity::Error,
        message: "[BR-Z-05]-In an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is \"Zero rated\" the Invoiced item VAT rate (BT-152) shall be 0 (zero).",
        check: Check::Vat(VatCheck::ZeroItemRate),
    },
    Rule {
        source: Source::Cen,
        site: "cen:096:BR-DEC-13",
        code: "BR-DEC-13",
        severity: Severity::Warning,
        message: "[BR-DEC-13]-The allowed maximum number of decimals for the Invoice total VAT amount (BT-110) is 2.",
        check: Check::TaxScale("DocumentCurrencyCode"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:097:BR-DEC-15",
        code: "BR-DEC-15",
        severity: Severity::Warning,
        message: "[BR-DEC-15]-The allowed maximum number of decimals for the Invoice total VAT amount in accounting currency (BT-111) is 2.",
        check: Check::TaxScale("TaxCurrencyCode"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:098:BR-CL-01",
        code: "BR-CL-01",
        severity: Severity::Error,
        message: "[BR-CL-01]-The document type code MUST be coded by the invoice and credit note related code lists of UNTDID 1001.",
        check: Check::CodeList(CodeListCheck::DocumentType),
    },
    Rule {
        source: Source::Cen,
        site: "cen:099:BR-CL-03",
        code: "BR-CL-03",
        severity: Severity::Error,
        message: "[BR-CL-03]-currencyID MUST be coded using ISO code list 4217 alpha-3",
        check: Check::CodeList(CodeListCheck::AmountCurrency),
    },
    Rule {
        source: Source::Cen,
        site: "cen:100:BR-CL-04",
        code: "BR-CL-04",
        severity: Severity::Error,
        message: "[BR-CL-04]-Invoice currency code MUST be coded using ISO code list 4217 alpha-3",
        check: Check::CodeList(CodeListCheck::DocumentCurrency),
    },
    Rule {
        source: Source::Cen,
        site: "cen:101:BR-CL-05",
        code: "BR-CL-05",
        severity: Severity::Error,
        message: "[BR-CL-05]-Tax currency code MUST be coded using ISO code list 4217 alpha-3",
        check: Check::CodeList(CodeListCheck::TaxCurrency),
    },
    Rule {
        source: Source::Cen,
        site: "cen:102:BR-CL-14",
        code: "BR-CL-14",
        severity: Severity::Warning,
        message: "[BR-CL-14]-Country codes in an invoice MUST be coded using ISO code list 3166-1",
        check: Check::CodeList(CodeListCheck::Country),
    },
    Rule {
        source: Source::Cen,
        site: "cen:103:BR-CL-16",
        code: "BR-CL-16",
        severity: Severity::Warning,
        message: "[BR-CL-16]-Payment means in an invoice MUST be coded using UNCL4461 code list",
        check: Check::CodeList(CodeListCheck::PaymentMeans),
    },
    Rule {
        source: Source::Cen,
        site: "cen:104:BR-CL-18",
        code: "BR-CL-18",
        severity: Severity::Error,
        message: "[BR-CL-18]-Invoice tax categories MUST be coded using UNCL5305 code list.",
        check: Check::CodeList(CodeListCheck::TaxCategory),
    },
    Rule {
        source: Source::Cen,
        site: "cen:105:BR-S-05",
        code: "BR-S-05",
        severity: Severity::Warning,
        message: "[BR-S-05]-For invoice items (BG-25) in which the VAT category code of invoiced items (BT-151) is \"Standard rated\" the VAT rate of the invoiced item (BT-152) must be greater than zero.",
        check: Check::Vat(VatCheck::StandardItemRate),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:001:BR-KSA-F-06-C3",
        code: "BR-KSA-F-06-C3",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C3] - Field character limits for Purchase order ID field (BT-13) have not been met. The maximum limit is 127 characters.",
        check: Check::KsaCommon(KsaCommonCheck::OrderReferenceLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:003:BR-KSA-F-06-C5",
        code: "BR-KSA-F-06-C5",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C5] - Field character limits for Contract ID field (BT-12) have not been met. The maximum limit is 127 characters .",
        check: Check::KsaCommon(KsaCommonCheck::ContractReferenceLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:004:BR-KSA-03",
        code: "BR-KSA-03",
        severity: Severity::Error,
        message: "[BR-KSA-03]-The invoice must contain a unique identifier (\"UUID\") (KSA-1) given by the unit that issued the document (unique message identifier for interchange process). This value must contain only letters, digits, and dashes.",
        check: Check::KsaCommon(KsaCommonCheck::Uuid),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:005:BR-KSA-27",
        code: "BR-KSA-27",
        severity: Severity::Warning,
        message: "[BR-KSA-27]-The document must contain a QR code (KSA-14), and this code must be base64Binary.",
        check: Check::KsaCommon(KsaCommonCheck::QrReference),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:006:BR-CL-KSA-14",
        code: "BR-CL-KSA-14",
        severity: Severity::Error,
        message: "[KSA-14]Field character limit for QR Code field has been exceeded. The maximum character limit for this field is 1000 characters.",
        check: Check::KsaCommon(KsaCommonCheck::QrLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:007:BR-KSA-33",
        code: "BR-KSA-33",
        severity: Severity::Error,
        message: "[BR-KSA-33]-Each invoice must have an invoice counter value (KSA-16).",
        check: Check::KsaCommon(KsaCommonCheck::InvoiceCounter),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:008:BR-KSA-92",
        code: "BR-KSA-92",
        severity: Severity::Error,
        message: "[BR-KSA-92]-If it's a B2G invoice transaction type (KSA 2, position 9 = 01), then the\n                           Contract ID (BT-12) must be present in a tax invoice and associated credit notes and debit notes\n                           (KSA-2, position 1 and 2 = 01).\n                        ",
        check: Check::KsaCommon(KsaCommonCheck::ContractReference),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:009:BR-KSA-34",
        code: "BR-KSA-34",
        severity: Severity::Error,
        message: "[BR-KSA-34]-The invoice counter value (KSA-16) contains only digits.",
        check: Check::KsaCommon(KsaCommonCheck::CounterDigits),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:010:BR-CUSTOM-VALIDATION-01",
        code: "BR-CUSTOM-VALIDATION-01",
        severity: Severity::Error,
        message: "[BR-CUSTOM-VALIDATION-01]- The Seller VAT registration number or seller group VAT registration number (BT-31) of The invoice must not match the buyer VAT registration number (BT-48) .",
        check: Check::KsaCommon(KsaCommonCheck::DifferentVatNumbers),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:011:BR-KSA-39",
        code: "BR-KSA-39",
        severity: Severity::Error,
        message: "[BR-KSA-39]-The invoice must contain the seller VAT registration number or seller group VAT registration number (BT-31).",
        check: Check::KsaCommon(KsaCommonCheck::SellerVat),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:012:BR-KSA-08",
        code: "BR-KSA-08",
        severity: Severity::Warning,
        message: "[BR-KSA-08]-The seller identification (BT-29) must exist only once with one of the scheme ID (BT-29-1) (CRN, MOM, MLS, SAG, OTH, 700) and must contain only alphanumeric characters. Commercial Registration number with \"CRN\" as schemeID. MOMRAH license with \"MOM\" as schemeID. MHRSD license with \"MLS\" as schemeID. 700 Number with \"700\" as schemeID. MISA license with \"SAG\" as schemeID. Other OD with \"OTH\" as schemeID. In case of multiple commercial registrations, the seller should fill the commercial registration of the branch in respect of which the Tax Invoice is being issued. In case multiple IDs exist then one of the above must be entered following the sequence specified above.",
        check: Check::KsaCommon(KsaCommonCheck::SellerScheme),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:013:BR-KSA-61",
        code: "BR-KSA-61",
        severity: Severity::Warning,
        message: "[BR-KSA-61]-Previous invoice hash (KSA-13) must exist in an invoice.",
        check: Check::KsaCommon(KsaCommonCheck::PreviousHash),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:014:BR-KSA-68",
        code: "BR-KSA-68",
        severity: Severity::Error,
        message: "[BR-KSA-68]-Tax currency code (BT-6) must exist in an invoice.",
        check: Check::KsaCommon(KsaCommonCheck::TaxCurrency),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:015:BR-KSA-CL-06",
        code: "BR-KSA-CL-06",
        severity: Severity::Warning,
        message: "[BR-KSA-CL-06]-Code for the reason for document level charge (BT-105) and the code for the reason for invoice line charge (BT-145) MUST be coded using UNTDID 7161 code list. https://unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred7161.htm",
        check: Check::KsaCommon(KsaCommonCheck::ChargeReasonCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:032:BR-KSA-49",
        code: "BR-KSA-49",
        severity: Severity::Error,
        message: "[BR-KSA-49]-If the tax exemption reason code (BT-121) is equal to VATEX-SA-EDU or VATEX-SA-HEA, then the other buyer ID (BT-46) is mandatory and must be national ID (BT-46-1 = NAT).",
        check: Check::KsaCommon(KsaCommonCheck::NationalBuyer),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:034:BR-KSA-05",
        code: "BR-KSA-05",
        severity: Severity::Error,
        message: "[BR-KSA-05]-The invoice type code (BT-3) must be equal to one of value from the subset of UN/CEFACT code list 1001, D.16B agreed for KSA electronic invoices. Please refer paragraph 11.2.1 of XML implementation Standards.",
        check: Check::KsaField(KsaFieldCheck::InvoiceType),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:035:BR-KSA-06",
        code: "BR-KSA-06",
        severity: Severity::Error,
        message: "[BR-KSA-06]-The invoice transaction code (KSA-2) must exist and respect the following structure:\n                        NNPNESBCG\n                        where\n                        NN (positions 1 and 2) = invoice subtype:\n                        - 01 for tax invoice\n                        - 02 for simplified tax invoice\n                        P (position 3) = 3rd Party invoice transaction, 0 for false, 1 for true;\n                        N (position 4) = Nominal invoice transaction, 0 for false, 1 for true;\n                        E (position 5) = Exports invoice transaction, 0 for false, 1 for true;\n                        S (position 6) = Summary invoice transaction, 0 for false, 1 for true;\n                        B (position 7) = Self billed invoice transaction, 0 for false, 1 for true;\n                        C (position 8) = Continuous Supply invoice transaction, 0 for false, 1 for true;\n                        G (position 9) = B2G invoice transaction, 0 for false, 1 for true\n                     ",
        check: Check::KsaField(KsaFieldCheck::TransactionCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:036:BR-KSA-F-06-C40",
        code: "BR-KSA-F-06-C40",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C40]-Field character limits for Invoice transaction code (KSA-2) have not been met. The minimum limit is 7 characters and the maximum limit is 9 characters.",
        check: Check::KsaField(KsaFieldCheck::TransactionLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:037:BR-KSA-F-08",
        code: "BR-KSA-F-08",
        severity: Severity::Warning,
        message: "[BR-KSA-F-08] - The value provided in Other Seller ID (BT-29) or Other Buyer ID (BT-46) for the scheme ID 'CRN' appears to be\n                  incorrect. Please recheck the value to avoid non-compliance.\n               ",
        check: Check::Identity(IdentityCheck::Crn),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:038:BR-KSA-F-09",
        code: "BR-KSA-F-09",
        severity: Severity::Warning,
        message: "[BR-KSA-F-09] - The value provided in Other Seller ID (BT-29) or Other Buyer ID (BT-46) for the scheme ID '700' appears to be incorrect. Please recheck the value to avoid non-compliance.",
        check: Check::Identity(IdentityCheck::UnifiedId),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:039:BR-KSA-F-12",
        code: "BR-KSA-F-12",
        severity: Severity::Warning,
        message: "\n                  [BR-KSA-F-12] - The Other Seller/Buyer schema ID (BT-29-1 or BT-46-1) contains spaces. Please recheck the attribute and remove the empty space to avoid non-compliance.\n               ",
        check: Check::Identity(IdentityCheck::SchemeWhitespace),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:040:BR-KSA-F-13",
        code: "BR-KSA-F-13",
        severity: Severity::Warning,
        message: "\n                  [BR-KSA-F-13] - Please recheck Other Seller/Buyer ID (BT-29 or BT-46) as it contains an invalid value.\n               ",
        check: Check::Identity(IdentityCheck::PredictableId),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:041:BR-KSA-14",
        code: "BR-KSA-14",
        severity: Severity::Error,
        message: "[BR-KSA-14]-The buyer identification (BT-46), required only if buyer is not VAT registered, then the buyer identification (BT-46) must be provided with one of the scheme IDs (BT-46-1) (TIN, CRN, MOM, MLS, 700, SAG, NAT, GCC, IQA, PAS, OTH) and must contain only alphanumeric characters. Tax Identification Number \"TIN\" as schemeID ;Commercial registration number with \"CRN\" as schemeID ;MOMRAH license with \"MOM\" as schemeID ;MHRSD license with \"MLS\" as schemeID ;700 Number with \"700\" as schemeID ;MISA license with \"SAG\" as schemeID ;National ID with \"NAT\" as schemeID ;GCC ID with \"GCC\" as schemeID ;Iqama Number with \"IQA\" as schemeID ;Passport ID with \"PAS\" as schemeID ;Other ID with \"OTH\" as schemeID. ;In case of multiple commercial registrations, the seller should fill the commercial registration of the branch in respect of which the Tax Invoice is being issued. In case multiple IDs exist then one of the above must be entered following the sequence specified above",
        check: Check::Identity(IdentityCheck::BuyerScheme),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:042:BR-KSA-F-07",
        code: "BR-KSA-F-07",
        severity: Severity::Warning,
        message: "[BR-KSA-F-07] - The value provided in Other Buyer ID (BT-46) for scheme ID 'TIN' appears to be incorrect. Please recheck the value to avoid non-compliance.\n                     ",
        check: Check::Identity(IdentityCheck::BuyerTin),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:043:BR-KSA-F-10",
        code: "BR-KSA-F-10",
        severity: Severity::Warning,
        message: "[BR-KSA-F-10] - The value provided in Other Buyer ID (BT-46) for the scheme ID 'NAT' appears to be incorrect. Please recheck the value to avoid non-compliance.",
        check: Check::Identity(IdentityCheck::BuyerNationalId),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:044:BR-KSA-F-11",
        code: "BR-KSA-F-11",
        severity: Severity::Warning,
        message: "[BR-KSA-F-11] - The value provided in Other Buyer ID (BT-46) for the scheme ID 'IQA' appears to be incorrect. Please recheck the value to avoid non-compliance. ",
        check: Check::Identity(IdentityCheck::BuyerResidenceId),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:045:BR-KSA-F-06-C4",
        code: "BR-KSA-F-06-C4",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C4] - Field character limits for the Seller Address - Street field (BT-35) have not been met. The minimum limit is 1 character and the maximum limit is 1000 characters.",
        check: Check::Identity(IdentityCheck::SellerStreet),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:046:BR-KSA-09",
        code: "BR-KSA-09",
        severity: Severity::Warning,
        message: "[BR-KSA-09]-Seller address must contain street name (BT-35), building number (KSA-17), postal code (BT-38), city (BT-37), district (KSA-3), country code (BT-40). For more information please access this link: https://splonline.com.sa/en/national-address-1/",
        check: Check::Identity(IdentityCheck::SellerAddress),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:047:BR-KSA-F-06-C11",
        code: "BR-KSA-F-06-C11",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C11] - Field character limits for the Buyer Address - Additional street field (BT-51) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::Identity(IdentityCheck::BuyerAdditionalStreet),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:048:BR-KSA-F-06-C7",
        code: "BR-KSA-F-06-C7",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C7] - Field character limits for the Seller Address - City field (BT-37) have not been met. The minimum limit is 1 character and the maximum limit is 127 characters.\n                     ",
        check: Check::Identity(IdentityCheck::SellerCity),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:049:BR-KSA-F-06-C6",
        code: "BR-KSA-F-06-C6",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C6] - Field character limits for the Seller Address - Additional street field (BT-36) have not been met. The maximum limit is 127 characters.",
        check: Check::Identity(IdentityCheck::SellerAdditionalStreet),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:050:BR-KSA-66",
        code: "BR-KSA-66",
        severity: Severity::Warning,
        message: "[BR-KSA-66]-Seller postal code (BT-38) must be 5 digits.",
        check: Check::Identity(IdentityCheck::SellerPostcode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:051:BR-KSA-26",
        code: "BR-KSA-26",
        severity: Severity::Warning,
        message: "[BR-KSA-26]-If the invoice contains the previous invoice hash (KSA-13), this hash must be base64 encoded SHA256.\n                        The hash shall be computed using the following method as described in the ds:transforms block in the XML Invoice Specifications:\n                        1. Remove the <Invoice><ext:UBLExtensions/> block\n                        2. Remove the <Invoice><cac:AdditionalDocumentReference/> block where <cbc:ID/> = QR\n                        3. Remove the <Invoice><cac:Signature/> block\n                        4. Canonicalize the Invoice using the C14N11 standard\n                        5. Hash the resulting string using SHA256 to a binary object\n                        6. Base64 encode the binary object to generate the digest value\n                        For the first invoice, the previous invoice hash is \"NWZlY2ViNjZmZmM4NmYzOGQ5NTI3ODZjNmQ2OTZjNzljMmRiYzIzOWRkNGU5MWI0NjcyOWQ3M2EyN2ZiNTdlOQ==\", the equivalent for base64 encoded SHA256 of \"0\" (zero) character.",
        check: Check::KsaCommon(KsaCommonCheck::PreviousHashAttachment),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:052:BR-KSA-28",
        code: "BR-KSA-28",
        severity: Severity::Error,
        message: "[BR-KSA-28]-If the cryptographic stamp (KSA-15) exists in the invoice, this cryptographic stamp (KSA-15) must contain the exact  \"urn:oasis:names:specification:ubl:signature:1\" value for signature information ID.",
        check: Check::KsaCommon(KsaCommonCheck::SignatureInformation),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:053:BR-KSA-29",
        code: "BR-KSA-29",
        severity: Severity::Warning,
        message: "[BR-KSA-29]-If the cryptographic stamp (KSA-15) exists in the invoice, this  cryptographic stamp (KSA-15) must contain the exact  \"urn:oasis:names:specification:ubl:signature:Invoice\" value for referenced signature ID and signature ID.",
        check: Check::KsaCommon(KsaCommonCheck::SignatureReference),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:054:BR-KSA-30",
        code: "BR-KSA-30",
        severity: Severity::Error,
        message: "[BR-KSA-30]-The document cryptographic stamp (KSA-15) must contain the exact  \"urn:oasis:names:specification:ubl:dsig:enveloped:xades\" value for signature method.",
        check: Check::KsaCommon(KsaCommonCheck::SignatureMethod),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:055:BR-KSA-35",
        code: "BR-KSA-35",
        severity: Severity::Warning,
        message: "[BR-KSA-35]-If the invoice contains a supply end date (KSA-24), then the invoice must contain a supply date (KSA-5).",
        check: Check::KsaCommon(KsaCommonCheck::ActualDeliveryDate),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:057:BR-KSA-37",
        code: "BR-KSA-37",
        severity: Severity::Warning,
        message: "[BR-KSA-37]-The seller address building number must contain 4 digits.",
        check: Check::Identity(IdentityCheck::SellerBuilding),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:058:BR-KSA-40",
        code: "BR-KSA-40",
        severity: Severity::Error,
        message: "[BR-KSA-40]-If it exists in the invoice, the seller VAT registration number (BT-31) must contain 15 digits. The first and the last digits are \"3\"..",
        check: Check::Identity(IdentityCheck::SellerVat),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:059:BR-KSA-42",
        code: "BR-KSA-42",
        severity: Severity::Warning,
        message: "The buyer name (BT-44) must be present in the tax invoice and associated credit notes and debit notes (KSA-2, position 1 and 2 = 01). ",
        check: Check::KsaCommon(KsaCommonCheck::BuyerName),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:061:BR-KSA-18",
        code: "BR-KSA-18",
        severity: Severity::Error,
        message: "[BR-KSA-18]-VAT category code must contain one of the values (S, Z, E, O).",
        check: Check::KsaExemption(KsaExemptionCheck::VatCategoryCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:062:BR-KSA-F-06-C16",
        code: "BR-KSA-F-06-C16",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C16]-Field character limits for VAT exemption reason text field (BT-120) have not been met. The minimum limit is 1 character and the maximum limit is 1000 characters.",
        check: Check::KsaExemption(KsaExemptionCheck::ExemptionReasonLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:063:BR-KSA-63",
        code: "BR-KSA-63",
        severity: Severity::Warning,
        message: "[BR-KSA-63]-If the buyer country code (BT-55) is \"SA\", then these fields are mandatory:street name (BT-50), building number (KSA-18), postal code (BT-53), city (BT-52), District (KSA-4), country code (BT-55).For more information please access this link:https://splonline.com.sa/en/national-address-1/",
        check: Check::KsaBuyer(KsaBuyerCheck::SaAddress),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:064:BR-KSA-F-06-C28",
        code: "BR-KSA-F-06-C28",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C28] - Field character limits for the Buyer Address - District field (KSA-4) have not been met. The minimum limit is 1 character  and the maximum limit is 127 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::DistrictRequired),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:065:BR-KSA-F-06-C29",
        code: "BR-KSA-F-06-C29",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C29] - Field character limits for the Buyer Address - District field (KSA-4) have not been met. The maximum limit is 127 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::DistrictLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:066:BR-KSA-F-06-C9",
        code: "BR-KSA-F-06-C9",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C9] - Field character limits for the Seller Address - District field (KSA-3) have not been met. The minimum limit is 1 character and the maximum limit is 127 characters.\n                     ",
        check: Check::KsaBuyer(KsaBuyerCheck::SellerDistrict),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:067:BR-KSA-67",
        code: "BR-KSA-67",
        severity: Severity::Warning,
        message: "[BR-KSA-67]-If the buyer country code (BT-55) is \"SA\", then the Buyer postal code(BT-53) must be 5 digits.",
        check: Check::KsaBuyer(KsaBuyerCheck::Postcode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:068:BR-KSA-72",
        code: "BR-KSA-72",
        severity: Severity::Error,
        message: "If the Invoice is a simplified invoice type and is a summary invoice (KSA-2, position 1 and 2 = 02, position 6 = 1), then a supply date (KSA-5) and supply end date (KSA-24) must be present\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::SummaryDates),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:069:BR-KSA-52",
        code: "BR-KSA-52",
        severity: Severity::Error,
        message: "[BR-KSA-52]-The line VAT amount (KSA-11) is mandatory for tax invoice and associated credit notes and debit notes (KSA-2, position 1 and 2 = 01).",
        check: Check::KsaBuyer(KsaBuyerCheck::LineTax),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:070:BR-KSA-F-06-C23",
        code: "BR-KSA-F-06-C23",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C23] - Field character limits for the Buyer Address - Street field (BT-50) have not been met. The minimum limit is 1 character and the maximum limit is 1000 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::StreetRequired),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:071:BR-KSA-F-06-C25",
        code: "BR-KSA-F-06-C25",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C25] - Field character limits for the Buyer Address - City field (BT-52) have not been met. The minimum limit is 1 character and the maximum limit is 127 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::CityRequired),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:072:BR-KSA-F-06-C32",
        code: "BR-KSA-F-06-C32",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C32] - Field character limits for Buyer name field (BT-44) have not been met. The maximum limit is 1000 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::SimpleNameLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:073:BR-KSA-F-06-C12",
        code: "BR-KSA-F-06-C12",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C12] - Field character limits for Buyer name field (BT-44) have not been met. The minimum limit is 1 character and the maximum limit is 1000 characters.\n                     ",
        check: Check::KsaBuyer(KsaBuyerCheck::StandardNameLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:074:BR-KSA-53",
        code: "BR-KSA-53",
        severity: Severity::Error,
        message: "[BR-KSA-53]-The line amount with VAT (KSA-12) is mandatory for tax invoice and associated credit notes and debit notes (KSA-2, position 1 and 2 = 01).",
        check: Check::KsaBuyer(KsaBuyerCheck::LineInclusive),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:075:BR-KSA-F-06-C14",
        code: "BR-KSA-F-06-C14",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C14]Field character limits for Payment terms field (KSA-22) have not been met. The maximum limit is 1000 characters.",
        check: Check::KsaBuyer(KsaBuyerCheck::PaymentNoteLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:076:BR-KSA-F-06-C24",
        code: "BR-KSA-F-06-C24",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C24] - Field character limits for the Buyer Address - Street field (BT-50) have not been met. The maximum limit is 1000 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::SimpleStreetLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:077:BR-KSA-F-06-C26",
        code: "BR-KSA-F-06-C26",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C26] - Field character limits for the Buyer Address - City field (BT-52) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::KsaBuyer(KsaBuyerCheck::CityLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:078:BR-KSA-16",
        code: "BR-KSA-16",
        severity: Severity::Warning,
        message: "[BR-KSA-16]-Payment means code (BT-81) in an invoice exist, then it must contain one of the values from subset of UNTDID 4461 code list",
        check: Check::KsaBuyer(KsaBuyerCheck::PaymentCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:079:BR-KSA-10",
        code: "BR-KSA-10",
        severity: Severity::Warning,
        message: "[BR-KSA-10]-Where the Buyer Country Code (BT-55) is other than 'SA' Buyer address must contain a street (BT-50), city (BT-52), country code (BT-55). This rule does not apply on the simplified tax invoices and associated credit notes and debit notes (KSA-2, position 1 and 2 = 02).",
        check: Check::KsaBuyer(KsaBuyerCheck::BuyerAddress),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:080:BR-KSA-F-06-C15",
        code: "BR-KSA-F-06-C15",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C15] - Field character limits for Payment account identifier field (BT-84) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::KsaBuyer(KsaBuyerCheck::AccountLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:081:BR-KSA-15",
        code: "BR-KSA-15",
        severity: Severity::Warning,
        message: "[BR-KSA-15]-The tax invoice  ((invoice type code (BT-30) = 388) and (invoice transaction code (KSA-2) has \"01\" as first 2 digits)) must contain the supply date (KSA-5).",
        check: Check::KsaBuyer(KsaBuyerCheck::SupplyDate),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:082:BR-KSA-17",
        code: "BR-KSA-17",
        severity: Severity::Error,
        message: "[BR-KSA-17]-Debit and credit note (invoice type code (BT-3) is equal to 383 or 381) must contain the reason (KSA-10) for this invoice type issuing.",
        check: Check::KsaBuyer(KsaBuyerCheck::NoteReason),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:083:BR-KSA-17",
        code: "BR-KSA-17",
        severity: Severity::Error,
        message: "[BR-KSA-17]-Debit and credit note (invoice type code (BT-3) is equal to 383 or 381) must contain the reason (KSA-10) for this invoice type issuing.",
        check: Check::KsaBuyer(KsaBuyerCheck::MissingPayment),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:084:BR-KSA-F-06-C13",
        code: "BR-KSA-F-06-C13",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C13] - Field character limits for Reasons for issuance of credit / debit note field (KSA-10) have not been met. The minimum limit is 1 character and the maximum limit is 1000 characters .\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::NoteReasonLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:085:BR-KSA-56",
        code: "BR-KSA-56",
        severity: Severity::Warning,
        message: "[BR-KSA-56]-For credit notes ((BT-3) has the value of 381) and debit notes ((BT-3) has the value of 383), the billing reference ID (BT-25) is  mandatory.",
        check: Check::KsaBuyer(KsaBuyerCheck::NoteReference),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:086:BR-KSA-F-06-C22",
        code: "BR-KSA-F-06-C22",
        severity: Severity::Error,
        message: "[BR-KSA-F-06-C22]-Field character limits for Billing reference ID field (BT-25) have not been met. The minimum limit is 1 character and the maximum limit is 5000 characters.",
        check: Check::KsaBuyer(KsaBuyerCheck::NoteReferenceLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:087:BR-KSA-56",
        code: "BR-KSA-56",
        severity: Severity::Warning,
        message: "[BR-KSA-56]-For credit notes ((BT-3) has the value of 381) and debit notes ((BT-3) has the value of 383), the billing reference ID (BT-25) is  mandatory.",
        check: Check::KsaBuyer(KsaBuyerCheck::MissingReference),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:088:BR-KSA-25",
        code: "BR-KSA-25",
        severity: Severity::Warning,
        message: "[BR-KSA-25]-If it is a simplified tax invoice or an associated credit note or a debit note (KSA-2, position 1 and 2 = 02) and the tax exemption reason code (BT-121) is equal with VATEX-SA-EDU or VATEX-SA-HEA, then buyer name (BT-44) is mandatory.",
        check: Check::KsaBuyer(KsaBuyerCheck::SimpleBuyer),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:089:BR-KSA-31",
        code: "BR-KSA-31",
        severity: Severity::Error,
        message: "\n                        [BR-KSA-31]- For Simplified Tax Invoices and associated credit notes and debit notes (KSA-2, position 1 and 2 = 02), transaction types \"self-billing\" (KSA-2, position 7 = True) is not allowed.",
        check: Check::KsaBuyer(KsaBuyerCheck::SimpleFlags),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:090:BR-KSA-60",
        code: "BR-KSA-60",
        severity: Severity::Warning,
        message: "[BR-KSA-60]-Cryptographic stamp (KSA-15) must exist in simplified tax invoices and associated credit notes and debit notes (KSA-2, position 1 and 2 = 02).",
        check: Check::KsaBuyer(KsaBuyerCheck::Stamp),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:091:BR-KSA-71",
        code: "BR-KSA-71",
        severity: Severity::Warning,
        message: "If the Invoice is a simplified invoice type and is a summary invoice (KSA-2, position 1 and 2 = 02, position 6 = 1),then the buyer name must be present.",
        check: Check::KsaBuyer(KsaBuyerCheck::SummaryBuyer),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:092:BR-KSA-07",
        code: "BR-KSA-07",
        severity: Severity::Error,
        message: "[BR-KSA-07]-Self billing is not allowed (KSA-2, position 7 cannot be \"1\") for export invoices (KSA-2, position 5 = 1).",
        check: Check::KsaBuyer(KsaBuyerCheck::ExportSelfBilling),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:093:BR-KSA-99",
        code: "BR-KSA-99",
        severity: Severity::Warning,
        message: "If it exists in the invoice,  the buyer VAT registration number or buyer group VAT registration number (BT-48) should not be left empty in the tax invoice and associated credit notes and debit notes (KSA-2, position 1 and 2 = 01).",
        check: Check::KsaBuyer(KsaBuyerCheck::EmptyBuyerVat),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:094:BR-KSA-44",
        code: "BR-KSA-44",
        severity: Severity::Error,
        message: "[BR-KSA-44]-If it exists in the invoice,the buyer VAT registration number or buyer group VAT registration number (BT-48) must contain 15 digits. The first digit and the last digit is \"3\".",
        check: Check::Identity(IdentityCheck::BuyerVat),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:095:BR-KSA-DEC-01",
        code: "BR-KSA-DEC-01",
        severity: Severity::Error,
        message: "[BR-KSA-DEC-01]-The allowance percentage values (BT-94, BT-138) must be from 0.00 to 100.00, with maximum two decimal places. Only numerals are accepted, the percentage symbol (%) is not allowed.",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::AllowancePercentage),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:096:BR-KSA-19",
        code: "BR-KSA-19",
        severity: Severity::Warning,
        message: "[BR-KSA-19]-Each Document level charge (BG-21) shall have a code for the reason for document level charge (BT-105).",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::DocumentChargeReasonCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:097:BR-KSA-21",
        code: "BR-KSA-21",
        severity: Severity::Warning,
        message: "[BR-KSA-21]-Each Document level charge (BG-21) shall have a Reason for document level charge (BT-104).",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::DocumentChargeReason),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:098:BR-KSA-F-06-C33",
        code: "BR-KSA-F-06-C33",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C33] -Field character limits for Reason for the document level charge (BT-104) have not been met. The maximum limit is 1,000 characters. ",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::DocumentChargeReasonLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:099:BR-KSA-20",
        code: "BR-KSA-20",
        severity: Severity::Warning,
        message: "[BR-KSA-20]-Each Invoice line charge (BG-28) shall have a code for the reason for invoice line charge (BT-145).",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::LineChargeReasonCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:100:BR-KSA-22",
        code: "BR-KSA-22",
        severity: Severity::Warning,
        message: "[BR-KSA-22]- Each Invoice line charge (BG-28) shall have a Reason for invoice line charge (BT-144).",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::LineChargeReason),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:101:BR-KSA-F-06-C34",
        code: "BR-KSA-F-06-C34",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C34] -Field character limits for Reason for invoice line charge (BT-144) have not been met. The maximum limit is 1,000 characters. ",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::LineChargeReasonLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:102:BR-KSA-F-06-C35",
        code: "BR-KSA-F-06-C35",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C35] -Field character limits for Reason for the document level allowance (BT-97) have not been met. The maximum limit is 1,000 characters. ",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::DocumentAllowanceReasonLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:103:BR-KSA-11",
        code: "BR-KSA-11",
        severity: Severity::Error,
        message: "[BR-KSA-11]-An Invoice line (BG-25) where the VAT category code (BT-151) is \"Not subject to VAT\", an invoiced item VAT rate (BT-152) shall be 0 (zero), if exist.",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::LineOutsideRate),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:104:BR-KSA-12",
        code: "BR-KSA-12",
        severity: Severity::Warning,
        message: "[BR-KSA-12]-A Document level allowance (BG-20) where VAT category code (BT-95) is \"Not subject to VAT\", a Document level allowance VAT rate (BT-96) shall be 0 (Zero), if exist.",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::DocumentAllowanceOutsideRate),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:105:BR-KSA-13",
        code: "BR-KSA-13",
        severity: Severity::Warning,
        message: "[BR-KSA-13]-A Document level charge (BG-21) where the VAT category code (BT-102) is \"Not subject to VAT\", a Document level charge VAT rate (BT-103) shall be 0 (zero), if exist.",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::DocumentChargeOutsideRate),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:106:BR-KSA-F-06-C36",
        code: "BR-KSA-F-06-C36",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C36] -Field character limits for Reason for the invoice line allowance (BT-139) have not been met. The maximum limit is 1,000 characters. ",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::LineAllowanceReasonLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:107:BR-KSA-81",
        code: "BR-KSA-81",
        severity: Severity::Warning,
        message: "[BR-KSA-81]-The other Buyer ID (BT-46) must present in the tax invoice and associated debit notes and credit notes (KSA-2, position 1 and 2 = 01), where the buyer VAT registration number or buyer group VAT registration number (BT-48) is not provided.",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::BuyerOtherId),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:108:BR-KSA-DEC-02",
        code: "BR-KSA-DEC-02",
        severity: Severity::Error,
        message: "[BR-KSA-DEC-02]-The VAT rates (BT-96, BT-103, BT-119, BT-152, KSA-34) must be from 0.00 to 100.00, with maximum two decimals.Only numerals are accepted, the percentage symbol (%) is not allowed.",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::TaxPercentage),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:109:BR-KSA-DEC-03",
        code: "BR-KSA-DEC-03",
        severity: Severity::Warning,
        message: "[BR-KSA-DEC-03]-VAT amount at line level (KSA-11) must have a maximum two decimals.",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::LineTaxScale),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:110:BR-KSA-DEC-04",
        code: "BR-KSA-DEC-04",
        severity: Severity::Warning,
        message: "[BR-KSA-DEC-04]-Amount with VAT at line level (KSA-12) must have a maximum two decimals.",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::LineInclusiveScale),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:113:BR-KSA-CL-03",
        code: "BR-KSA-CL-03",
        severity: Severity::Error,
        message: "[BR-KSA-CL-03]-Mime code must be according to subset of IANA code list.",
        check: Check::KsaExemption(KsaExemptionCheck::MimeCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:114:BR-KSA-83",
        code: "BR-KSA-83",
        severity: Severity::Warning,
        message: "[BR-KSA-83]-A VAT breakdown (BG-23) with VAT Category code (BT-118) 'Exempt from VAT' or 'Zero rated' or 'Not subject to VAT' shall have a VAT exemption (or exception) reason text (BT-120) with one of the values from paragraph 11.2.4 of XML implementation standards on Tax exemption (or exception) reason text - specific to Saudi Arabia. ",
        check: Check::KsaExemption(KsaExemptionCheck::ExemptionReason),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:115:BR-KSA-CL-04",
        code: "BR-KSA-CL-04",
        severity: Severity::Warning,
        message: "[BR-KSA-CL-04]-If VAT category Code (BT-118) is 'Z', or 'E', VAT exemption (or exception) reason code (BT-121) must exist with one of the values from paragraph 11.2.4 of XML implementation standards on Tax exemption (or exception) reason code - specific to Saudi Arabia. ",
        check: Check::KsaExemption(KsaExemptionCheck::ExemptionCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:116:BR-KSA-24",
        code: "BR-KSA-24",
        severity: Severity::Warning,
        message: "[BR-KSA-24]-A VAT breakdown (BG-23) with VAT Category code (BT-118) 'Not subject to VAT' shall have a VAT exception reason code (BT-121)",
        check: Check::KsaExemption(KsaExemptionCheck::OutsideScopeCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:117:BR-KSA-23",
        code: "BR-KSA-23",
        severity: Severity::Warning,
        message: "[BR-KSA-23]-A VAT breakdown (BG-23) with VAT Category code (BT-118) 'Exempt from VAT' shall have a VAT exemption reason code (BT-121).",
        check: Check::KsaExemption(KsaExemptionCheck::ExemptCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:118:BR-KSA-69",
        code: "BR-KSA-69",
        severity: Severity::Warning,
        message: "[BR-KSA-69]-A VAT breakdown (BG-23) with VAT Category code (BT-118) 'Zero rated' shall have a VAT exception reason code (BT-121).",
        check: Check::KsaExemption(KsaExemptionCheck::ZeroRatedCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:119:BR-KSA-84",
        code: "BR-KSA-84",
        severity: Severity::Error,
        message: "The Document level allowance VAT rate (BT-96), Document level Charge VAT rate (BT-103), VAT category rate(BT-119), Invoiced item VAT rate (BT-152), Prepayment VAT rate(KSA-34) must be limited to one of the following values (5 or 15) when the relevant Document level allowance VAT category code (BT-95), Document level Charge VAT category code(BT-102), VAT category code(BT-118), Invoiced item VAT category code(BT-151), Prepayment VAT Category Code (KSA-33) is \"S\"- \"Standard rated\".  In other words, for Standard Rate VAT Category the rate can either be 15% or 5%. ",
        check: Check::KsaExemption(KsaExemptionCheck::AllowanceStandardRate),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:120:BR-KSA-84",
        code: "BR-KSA-84",
        severity: Severity::Error,
        message: "The Document level allowance VAT rate (BT-96), Document level Charge VAT rate (BT-103), VAT category rate(BT-119), Invoiced item VAT rate (BT-152), Prepayment VAT rate(KSA-34) must be limited to one of the following values (5 or 15) when the relevant Document level allowance VAT category code (BT-95), Document level Charge VAT category code(BT-102), VAT category code(BT-118), Invoiced item VAT category code(BT-151), Prepayment VAT Category Code (KSA-33) is \"S\"- \"Standard rated\".  In other words, for Standard Rate VAT Category the rate can either be 15% or 5%. ",
        check: Check::KsaExemption(KsaExemptionCheck::BreakdownStandardRate),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:121:BR-KSA-84",
        code: "BR-KSA-84",
        severity: Severity::Error,
        message: "The Document level allowance VAT rate (BT-96), Document level Charge VAT rate (BT-103), VAT category rate(BT-119), Invoiced item VAT rate (BT-152), Prepayment VAT rate(KSA-34) must be limited to one of the following values (5 or 15) when the relevant Document level allowance VAT category code (BT-95), Document level Charge VAT category code(BT-102), VAT category code(BT-118), Invoiced item VAT category code(BT-151), Prepayment VAT Category Code (KSA-33) is \"S\"- \"Standard rated\".  In other words, for Standard Rate VAT Category the rate can either be 15% or 5%. ",
        check: Check::KsaExemption(KsaExemptionCheck::ItemStandardRate),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:122:BR-KSA-84",
        code: "BR-KSA-84",
        severity: Severity::Error,
        message: "The Document level allowance VAT rate (BT-96), Document level Charge VAT rate (BT-103), VAT category rate(BT-119), Invoiced item VAT rate (BT-152), Prepayment VAT rate(KSA-34) must be limited to one of the following values (5 or 15) when the relevant Document level allowance VAT category code (BT-95), Document level Charge VAT category code(BT-102), VAT category code(BT-118), Invoiced item VAT category code(BT-151), Prepayment VAT Category Code (KSA-33) is \"S\"- \"Standard rated\".  In other words, for Standard Rate VAT Category the rate can either be 15% or 5%. ",
        check: Check::KsaExemption(KsaExemptionCheck::PrepaymentStandardRate),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:123:BR-KSA-93",
        code: "BR-KSA-93",
        severity: Severity::Warning,
        message: "[BR-KSA-93]-An Invoice line (BG-25) where the Prepayment VAT category code (KSA-33) is \"Zero-rated\" the Prepayment VAT exception reason code (KSA-41) should be provided.",
        check: Check::KsaExemption(KsaExemptionCheck::PrepaymentZeroRatedCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:124:BR-KSA-94",
        code: "BR-KSA-94",
        severity: Severity::Warning,
        message: "[BR-KSA-94]-An Invoice line (BG-25) where the Prepayment VAT category code (KSA-33) is \" Exempt from VAT \" the Prepayment VAT exemption reason code (KSA-41) should be provided.",
        check: Check::KsaExemption(KsaExemptionCheck::PrepaymentExemptCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:125:BR-KSA-95",
        code: "BR-KSA-95",
        severity: Severity::Warning,
        message: "[BR-KSA-95]-An Invoice line (BG-25) where the Prepayment VAT category code (KSA-33) is \" Not subject to VAT \" the Prepayment VAT exception reason code (KSA-41) should be provided.",
        check: Check::KsaExemption(KsaExemptionCheck::PrepaymentOutsideScopeCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:126:BR-KSA-96",
        code: "BR-KSA-96",
        severity: Severity::Warning,
        message: "[BR-KSA-96]-An Invoice line (BG-25) with the Prepayment VAT category code (KSA-33) 'Exempt from VAT' or 'Zero rated' or 'Not subject to VAT' shall have a Prepayment VAT exemption(or exception) reason text (KSA-42) with one of the values from paragraph 11.2.4 of XML implementation standards on Tax exemption (or exception) reason text - specific to Saudi Arabia. ",
        check: Check::KsaExemption(KsaExemptionCheck::PrepaymentExemptionReason),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:127:BR-KSA-CL-07",
        code: "BR-KSA-CL-07",
        severity: Severity::Warning,
        message: "[BR-KSA-CL-07]-If the Prepayment VAT Category Code(KSA-33) is 'Z', or 'E' or 'O', the Prepayment VAT exemption (or exception) reason code(KSA-41) must exist with one of the values from paragraph 11.2.4 of XML implementation standards on Tax exemption (or exception) reason code - specific to Saudi Arabia. ",
        check: Check::KsaExemption(KsaExemptionCheck::PrepaymentExemptionCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:128:BR-KSA-F-06-C39",
        code: "BR-KSA-F-06-C39",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C39] - Field character limits for the Prepayment VAT exemption reason text (KSA-42) have not been met. The maximum limit is 1000 characters.",
        check: Check::KsaExemption(KsaExemptionCheck::PrepaymentExemptionReasonLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:133:BR-KSA-EN16931-01",
        code: "BR-KSA-EN16931-01",
        severity: Severity::Error,
        message: "[BR-KSA-EN16931-01]-Business process (BT-23) must be \"reporting:1.0\".",
        check: Check::KsaField(KsaFieldCheck::Profile),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:134:BR-KSA-EN16931-08",
        code: "BR-KSA-EN16931-08",
        severity: Severity::Warning,
        message: "[BR-KSA-EN16931-08]-Only one tax total (BG-22) with tax subtotals must be provided.Refer to Calculation of VAT.",
        check: Check::KsaField(KsaFieldCheck::TaxSubtotalTotal),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:136:BR-KSA-EN16931-02",
        code: "BR-KSA-EN16931-02",
        severity: Severity::Error,
        message: "[BR-KSA-EN16931-02]-VAT accounting currency code (BT-6) must be \"SAR\".",
        check: Check::TaxCurrency,
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:137:BR-KSA-EN16931-09",
        code: "BR-KSA-EN16931-09",
        severity: Severity::Warning,
        message: "[BR-KSA-EN16931-09]-Only one tax total (BG-22) without tax subtotals (BG-23) must be provided when tax currency code is provided .",
        check: Check::BareTaxTotal,
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:139:BR-KSA-EN16931-05",
        code: "BR-KSA-EN16931-05",
        severity: Severity::Warning,
        message: "[BR-KSA-EN16931-05]-Allowance/Charge percentage (BT-94, BT-101, BT-138, BT-143) must be provided when the allowance/Charge base amount (BT-93, BT-100, BT-137, BT-142) is provided.",
        check: Check::KsaField(KsaFieldCheck::BasePercentage),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:140:BR-KSA-EN16931-04",
        code: "BR-KSA-EN16931-04",
        severity: Severity::Warning,
        message: "[BR-KSA-EN16931-04]-Allowance/Charge base amount (BT-93, BT-100, BT-137, BT-142) must be provided when allowance/Charge percentage (BT-94, BT-101,BT-138, BT-143) is provided.",
        check: Check::KsaField(KsaFieldCheck::PercentageBase),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:141:BR-KSA-EN16931-06",
        code: "BR-KSA-EN16931-06",
        severity: Severity::Error,
        message: "[BR-KSA-EN16931-06]-Charge on price level (BG-29) is not allowed. The value of Indicator should be 'false'.",
        check: Check::KsaField(KsaFieldCheck::NoPriceCharge),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:143:BR-KSA-F-06-C21",
        code: "BR-KSA-F-06-C21",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C21] - Field character limits for Item price base quantity unit code field (BT-150) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::KsaField(KsaFieldCheck::BaseUnitLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:144:BR-KSA-EN16931-12",
        code: "BR-KSA-EN16931-12",
        severity: Severity::Error,
        message: "[BR-KSA-EN16931-12]-Base quantity (BT-149) must be a positive number above zero.",
        check: Check::KsaField(KsaFieldCheck::PositiveBaseQuantity),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:145:BR-KSA-EN16931-07",
        code: "BR-KSA-EN16931-07",
        severity: Severity::Error,
        message: "[BR-KSA-EN16931-07]-Item net price (BT-146) must equal (Item Gross price (BT-148) - Allowance amount (BT-147)) when gross price is provided.",
        check: Check::KsaAdjustment(KsaAdjustmentCheck::GrossNet),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:146:BR-KSA-85",
        code: "BR-KSA-85",
        severity: Severity::Warning,
        message: "[BR-KSA-85]-The Buyer's contact phone number (BT-57) shall start with \"0\" or \"+\", followed by a maximum of 15 number and minimum 4 character after the \"+\" or \"0\" , if exist.",
        check: Check::Identity(IdentityCheck::BuyerPhone),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:147:BR-KSA-F-06-C37",
        code: "BR-KSA-F-06-C37",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C37] - Field character limits for the contact name - Buyer's contact point field (BT-56) have not been met. The maximum limit is 1000 characters.\n                     ",
        check: Check::Identity(IdentityCheck::ContactName),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:148:BR-KSA-F-06-C38",
        code: "BR-KSA-F-06-C38",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C38] - Field character limits for the contact note - Buyer's Contact Note field (KSA-35) have not been met. The maximum limit is 1000 characters.\n                     ",
        check: Check::Identity(IdentityCheck::ContactNote),
    },
];
