//! Metadata extracted from the SDK 238-R3.4.8 catalog for the implemented slice.
//! Imported rule messages retain their recorded LGPL-3.0 terms.
//! See THIRD_PARTY_NOTICES.md and the business-rules fixture NOTICE.md.
//! The catalog regression test detects drift in source, site, message or severity.
use super::{Severity, Source, rules::Check};

pub(super) struct Rule {
    pub source: Source,
    pub site: &'static str,
    pub code: &'static str,
    pub message: &'static str,
    pub severity: Severity,
    pub check: Check,
}

pub(super) const RULES: &[Rule] = &[
    Rule {
        source: Source::Cen,
        site: "cen:016:BR-CO-10",
        code: "BR-CO-10",
        severity: Severity::Warning,
        message: "[BR-CO-10]-Sum of Invoice line net amount (BT-106) = Σ Invoice line net amount (BT-131).",
        check: Check::LineSum,
    },
    Rule {
        source: Source::Cen,
        site: "cen:023:BR-DEC-09",
        code: "BR-DEC-09",
        severity: Severity::Warning,
        message: "[BR-DEC-09]-The allowed maximum number of decimals for the Sum of Invoice line net amount (BT-106) is 2.",
        check: Check::TotalScale("LineExtensionAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:024:BR-DEC-10",
        code: "BR-DEC-10",
        severity: Severity::Warning,
        message: "[BR-DEC-10]-The allowed maximum number of decimals for the Sum of allowanced on document level (BT-107) is 2.",
        check: Check::TotalScale("AllowanceTotalAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:025:BR-DEC-11",
        code: "BR-DEC-11",
        severity: Severity::Warning,
        message: "[BR-DEC-11]-The allowed maximum number of decimals for the Sum of charges on document level (BT-108) is 2.",
        check: Check::TotalScale("ChargeTotalAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:026:BR-DEC-12",
        code: "BR-DEC-12",
        severity: Severity::Warning,
        message: "[BR-DEC-12]-The allowed maximum number of decimals for the Invoice total amount without VAT (BT-109) is 2.",
        check: Check::TotalScale("TaxExclusiveAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:027:BR-DEC-14",
        code: "BR-DEC-14",
        severity: Severity::Warning,
        message: "[BR-DEC-14]-The allowed maximum number of decimals for the Invoice total amount with VAT (BT-112) is 2.",
        check: Check::TotalScale("TaxInclusiveAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:028:BR-DEC-16",
        code: "BR-DEC-16",
        severity: Severity::Warning,
        message: "[BR-DEC-16]-The allowed maximum number of decimals for the Pre-Paid amount (BT-113) is 2.",
        check: Check::TotalScale("PrepaidAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:029:BR-DEC-17",
        code: "BR-DEC-17",
        severity: Severity::Warning,
        message: "[BR-DEC-17]-The allowed maximum number of decimals for the Rounding amount (BT-114) is 2.",
        check: Check::TotalScale("PayableRoundingAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:030:BR-DEC-18",
        code: "BR-DEC-18",
        severity: Severity::Warning,
        message: "[BR-DEC-18]-The allowed maximum number of decimals for the Amount due for payment (BT-115) is 2.  ",
        check: Check::TotalScale("PayableAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:048:BR-CO-15",
        code: "BR-CO-15",
        severity: Severity::Error,
        message: "[BR-CO-15]-Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).",
        check: Check::InclusiveTotal,
    },
    Rule {
        source: Source::Cen,
        site: "cen:062:BR-25",
        code: "BR-25",
        severity: Severity::Warning,
        message: "[BR-25]-Each Invoice line (BG-25) shall contain the Item name (BT-153).",
        check: Check::ItemName,
    },
    Rule {
        source: Source::Cen,
        site: "cen:067:BR-DEC-24",
        code: "BR-DEC-24",
        severity: Severity::Warning,
        message: "[BR-DEC-24]-The allowed maximum number of decimals for the Invoice line allowance amount (BT-136) is 2.",
        check: Check::LineAllowanceScale("Amount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:068:BR-DEC-25",
        code: "BR-DEC-25",
        severity: Severity::Warning,
        message: "[BR-DEC-25]-The allowed maximum number of decimals for the Invoice line allowance base amount (BT-137) is 2.",
        check: Check::LineAllowanceScale("BaseAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:073:BR-CO-14",
        code: "BR-CO-14",
        severity: Severity::Error,
        message: "[BR-CO-14]-Invoice total VAT amount (BT-110) = Σ VAT category tax amount (BT-117).",
        check: Check::TaxSum,
    },
    Rule {
        source: Source::Cen,
        site: "cen:096:BR-DEC-13",
        code: "BR-DEC-13",
        severity: Severity::Warning,
        message: "[BR-DEC-13]-The allowed maximum number of decimals for the Invoice total VAT amount (BT-110) is 2.",
        check: Check::TaxScale("DocumentCurrencyCode"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:097:BR-DEC-15",
        code: "BR-DEC-15",
        severity: Severity::Warning,
        message: "[BR-DEC-15]-The allowed maximum number of decimals for the Invoice total VAT amount in accounting currency (BT-111) is 2.",
        check: Check::TaxScale("TaxCurrencyCode"),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:136:BR-KSA-EN16931-02",
        code: "BR-KSA-EN16931-02",
        severity: Severity::Error,
        message: "[BR-KSA-EN16931-02]-VAT accounting currency code (BT-6) must be \"SAR\".",
        check: Check::TaxCurrency,
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:137:BR-KSA-EN16931-09",
        code: "BR-KSA-EN16931-09",
        severity: Severity::Warning,
        message: "[BR-KSA-EN16931-09]-Only one tax total (BG-22) without tax subtotals (BG-23) must be provided when tax currency code is provided .",
        check: Check::BareTaxTotal,
    },
];
