//! Metadata extracted from the SDK 238-R3.4.8 catalog for the implemented slice.
//! Imported rule messages retain their recorded LGPL-3.0 terms.
//! See THIRD_PARTY_NOTICES.md and the business-rules fixture NOTICE.md.
//! The catalog regression test detects drift in source, site, message or severity.
use super::{Severity, Source, identity::IdentityCheck, rules::Check};

pub(super) struct Rule {
    pub source: Source,
    pub site: &'static str,
    pub code: &'static str,
    pub message: &'static str,
    pub severity: Severity,
    pub check: Check,
}

use super::{
    structural::{Context as C, Requirement as R},
    xml::{a, b},
};

use super::code_lists::CodeListCheck;

use super::totals::TotalsCheck;

use super::ksa_fields::KsaFieldCheck;

use super::ksa_buyer::KsaBuyerCheck;

pub(super) const RULES: &[Rule] = &[
    Rule {
        source: Source::Cen,
        site: "cen:001:BR-52",
        code: "BR-52",
        severity: Severity::Warning,
        message: "[BR-52]-Each Additional supporting document (BG-24) shall contain a Supporting document reference (BT-122).",
        check: Check::Structural(
            C::All(&[a("AdditionalDocumentReference")]),
            R::Nonempty(&[b("ID")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:002:BR-31",
        code: "BR-31",
        severity: Severity::Error,
        message: "[BR-31]-Each Document level allowance (BG-20) shall have a Document level allowance amount (BT-92).",
        check: Check::Structural(C::DocumentAllowance(false), R::Exists(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:003:BR-32",
        code: "BR-32",
        severity: Severity::Error,
        message: "[BR-32]-Each Document level allowance (BG-20) shall have a Document level allowance VAT category code (BT-95).",
        check: Check::Structural(
            C::DocumentAllowance(false),
            R::VatCategory(&[a("TaxCategory")], true),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:004:BR-DEC-01",
        code: "BR-DEC-01",
        severity: Severity::Warning,
        message: "[BR-DEC-01]-The allowed maximum number of decimals for the Document level allowance amount (BT-92) is 2.",
        check: Check::Structural(C::DocumentAllowance(false), R::Scale(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:005:BR-DEC-02",
        code: "BR-DEC-02",
        severity: Severity::Warning,
        message: "[BR-DEC-02]-The allowed maximum number of decimals for the Document level allowance base amount (BT-93) is 2.",
        check: Check::Structural(C::DocumentAllowance(false), R::Scale(&[b("BaseAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:006:BR-36",
        code: "BR-36",
        severity: Severity::Warning,
        message: "[BR-36]-Each Document level charge (BG-21) shall have a Document level charge amount (BT-99).",
        check: Check::Structural(C::DocumentAllowance(true), R::Exists(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:007:BR-37",
        code: "BR-37",
        severity: Severity::Warning,
        message: "[BR-37]-Each Document level charge (BG-21) shall have a Document level charge VAT category code (BT-102).",
        check: Check::Structural(
            C::DocumentAllowance(true),
            R::Exists(&[a("TaxCategory"), b("ID")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:008:BR-DEC-06",
        code: "BR-DEC-06",
        severity: Severity::Warning,
        message: "[BR-DEC-06]-The allowed maximum number of decimals for the Document level charge base amount (BT-100) is 2.",
        check: Check::Structural(C::DocumentAllowance(true), R::Scale(&[b("BaseAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:009:BR-DEC-05",
        code: "BR-DEC-05",
        severity: Severity::Warning,
        message: "[BR-DEC-05]-The allowed maximum number of decimals for the Document level charge amount (BT-99) is 2.",
        check: Check::Structural(C::DocumentAllowance(true), R::Scale(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:010:BR-43",
        code: "BR-43",
        severity: Severity::Warning,
        message: "[BR-43]-Each Invoice line charge (BG-28) shall have an Invoice line charge amount (BT-141).",
        check: Check::Structural(C::LineCharge, R::Exists(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:011:BR-DEC-27",
        code: "BR-DEC-27",
        severity: Severity::Warning,
        message: "[BR-DEC-27]-The allowed maximum number of decimals for the Invoice line charge amount (BT-141) is 2.",
        check: Check::Structural(C::LineCharge, R::Scale(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:012:BR-DEC-28",
        code: "BR-DEC-28",
        severity: Severity::Warning,
        message: "[BR-DEC-28]-The allowed maximum number of decimals for the Invoice line charge base amount (BT-142) is 2.",
        check: Check::Structural(C::LineCharge, R::Scale(&[b("BaseAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:013:BR-13",
        code: "BR-13",
        severity: Severity::Warning,
        message: "[BR-13]-An Invoice shall have the Invoice total amount without VAT (BT-109).",
        check: Check::Structural(
            C::All(&[a("LegalMonetaryTotal")]),
            R::Exists(&[b("TaxExclusiveAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:014:BR-14",
        code: "BR-14",
        severity: Severity::Error,
        message: "[BR-14]-An Invoice shall have the Invoice total amount with VAT (BT-112).",
        check: Check::Structural(
            C::All(&[a("LegalMonetaryTotal")]),
            R::Exists(&[b("TaxInclusiveAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:015:BR-15",
        code: "BR-15",
        severity: Severity::Error,
        message: "[BR-15]-An Invoice shall have the Amount due for payment (BT-115).",
        check: Check::Structural(
            C::All(&[a("LegalMonetaryTotal")]),
            R::Exists(&[b("PayableAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:016:BR-CO-10",
        code: "BR-CO-10",
        severity: Severity::Warning,
        message: "[BR-CO-10]-Sum of Invoice line net amount (BT-106) = Σ Invoice line net amount (BT-131).",
        check: Check::LineSum,
    },
    Rule {
        source: Source::Cen,
        site: "cen:017:BR-CO-11",
        code: "BR-CO-11",
        severity: Severity::Error,
        message: "[BR-CO-11]-Sum of allowances on document level (BT-107) = Σ Document level allowance amount (BT-92).",
        check: Check::Totals(TotalsCheck::AllowanceSum),
    },
    Rule {
        source: Source::Cen,
        site: "cen:018:BR-CO-12",
        code: "BR-CO-12",
        severity: Severity::Error,
        message: "[BR-CO-12]-Sum of charges on document level (BT-108) = Σ Document level charge amount (BT-99).",
        check: Check::Totals(TotalsCheck::EmptyChargeSum),
    },
    Rule {
        source: Source::Cen,
        site: "cen:019:BR-CO-12",
        code: "BR-CO-12",
        severity: Severity::Error,
        message: "[BR-CO-12]-Sum of charges on document level (BT-108) = Σ Document level charge amount (BT-99).",
        check: Check::Totals(TotalsCheck::ChargeSum),
    },
    Rule {
        source: Source::Cen,
        site: "cen:020:BR-CO-13",
        code: "BR-CO-13",
        severity: Severity::Warning,
        message: "[BR-CO-13]-Invoice total amount without VAT (BT-109) = Σ Invoice line net amount (BT-131) - Sum of allowances on document level (BT-107) + Sum of charges on document level (BT-108).",
        check: Check::Totals(TotalsCheck::EmptyChargeExclusive),
    },
    Rule {
        source: Source::Cen,
        site: "cen:021:BR-CO-13",
        code: "BR-CO-13",
        severity: Severity::Warning,
        message: "[BR-CO-13]-Invoice total amount without VAT (BT-109) = Σ Invoice line net amount (BT-131) - Sum of allowances on document level (BT-107) + Sum of charges on document level (BT-108).",
        check: Check::Totals(TotalsCheck::Exclusive),
    },
    Rule {
        source: Source::Cen,
        site: "cen:022:BR-CO-16",
        code: "BR-CO-16",
        severity: Severity::Warning,
        message: "[BR-CO-16]-Amount due for payment (BT-115) = Invoice total amount with VAT (BT-112) -Pre-Paid amount (BT-113) + Rounding amount (BT-114).",
        check: Check::Totals(TotalsCheck::Payable),
    },
    Rule {
        source: Source::Cen,
        site: "cen:023:BR-DEC-09",
        code: "BR-DEC-09",
        severity: Severity::Warning,
        message: "[BR-DEC-09]-The allowed maximum number of decimals for the Sum of Invoice line net amount (BT-106) is 2.",
        check: Check::TotalScale("LineExtensionAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:024:BR-DEC-10",
        code: "BR-DEC-10",
        severity: Severity::Warning,
        message: "[BR-DEC-10]-The allowed maximum number of decimals for the Sum of allowanced on document level (BT-107) is 2.",
        check: Check::TotalScale("AllowanceTotalAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:025:BR-DEC-11",
        code: "BR-DEC-11",
        severity: Severity::Warning,
        message: "[BR-DEC-11]-The allowed maximum number of decimals for the Sum of charges on document level (BT-108) is 2.",
        check: Check::TotalScale("ChargeTotalAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:026:BR-DEC-12",
        code: "BR-DEC-12",
        severity: Severity::Warning,
        message: "[BR-DEC-12]-The allowed maximum number of decimals for the Invoice total amount without VAT (BT-109) is 2.",
        check: Check::TotalScale("TaxExclusiveAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:027:BR-DEC-14",
        code: "BR-DEC-14",
        severity: Severity::Warning,
        message: "[BR-DEC-14]-The allowed maximum number of decimals for the Invoice total amount with VAT (BT-112) is 2.",
        check: Check::TotalScale("TaxInclusiveAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:028:BR-DEC-16",
        code: "BR-DEC-16",
        severity: Severity::Warning,
        message: "[BR-DEC-16]-The allowed maximum number of decimals for the Pre-Paid amount (BT-113) is 2.",
        check: Check::TotalScale("PrepaidAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:029:BR-DEC-17",
        code: "BR-DEC-17",
        severity: Severity::Warning,
        message: "[BR-DEC-17]-The allowed maximum number of decimals for the Rounding amount (BT-114) is 2.",
        check: Check::TotalScale("PayableRoundingAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:030:BR-DEC-18",
        code: "BR-DEC-18",
        severity: Severity::Warning,
        message: "[BR-DEC-18]-The allowed maximum number of decimals for the Amount due for payment (BT-115) is 2.  ",
        check: Check::TotalScale("PayableAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:031:BR-02",
        code: "BR-02",
        severity: Severity::Warning,
        message: "[BR-02]-An Invoice shall have an Invoice number (BT-1).",
        check: Check::Structural(C::Root, R::Nonempty(&[b("ID")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:032:BR-KSA-F-06-C1",
        code: "BR-KSA-F-06-C1",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C1] - Field character limits for Invoice number field (BT-1) have not been met. The minimum limit is 1 character and the maximum limit is 127 characters.",
        check: Check::Structural(C::Root, R::Length(&[b("ID")], 0, 127)),
    },
    Rule {
        source: Source::Cen,
        site: "cen:033:BR-KSA-F-06-C2",
        code: "BR-KSA-F-06-C2",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C2] - Field character limits for Invoice note field (BT-22) have not been met. The maximum limit is 1000 characters.",
        check: Check::Structural(C::Root, R::InvoiceNote),
    },
    Rule {
        source: Source::Cen,
        site: "cen:034:BR-03",
        code: "BR-03",
        severity: Severity::Error,
        message: "[BR-03]-An Invoice shall have an Invoice issue date (BT-2).",
        check: Check::Structural(C::Root, R::Nonempty(&[b("IssueDate")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:035:BR-04",
        code: "BR-04",
        severity: Severity::Error,
        message: "[BR-04]-An Invoice shall have an Invoice type code (BT-3).",
        check: Check::Structural(C::Root, R::InvoiceType),
    },
    Rule {
        source: Source::Cen,
        site: "cen:036:BR-05",
        code: "BR-05",
        severity: Severity::Error,
        message: "[BR-05]-An Invoice shall have an Invoice currency code (BT-5).",
        check: Check::Structural(C::Root, R::Nonempty(&[b("DocumentCurrencyCode")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:037:BR-06",
        code: "BR-06",
        severity: Severity::Warning,
        message: "[BR-06]-An Invoice shall contain the Seller name (BT-27).",
        check: Check::Structural(
            C::Root,
            R::Nonempty(&[
                a("AccountingSupplierParty"),
                a("Party"),
                a("PartyLegalEntity"),
                b("RegistrationName"),
            ]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:038:BR-KSA-F-06-C10",
        code: "BR-KSA-F-06-C10",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C10] - Field character limits for Seller name field (BT-27) have not been met. The minimum limit is 1 character and the maximum limit is 1000 characters.\n                        ",
        check: Check::Structural(
            C::Root,
            R::Length(
                &[
                    a("AccountingSupplierParty"),
                    a("Party"),
                    a("PartyLegalEntity"),
                    b("RegistrationName"),
                ],
                1,
                1000,
            ),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:039:BR-KSA-F-06-C8",
        code: "BR-KSA-F-06-C8",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C8] - Field character limits for the Seller Address - Province/State field (BT-39) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::Structural(
            C::Root,
            R::Length(
                &[
                    a("AccountingSupplierParty"),
                    a("Party"),
                    a("PostalAddress"),
                    b("CountrySubentity"),
                ],
                0,
                127,
            ),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:040:BR-08",
        code: "BR-08",
        severity: Severity::Warning,
        message: "[BR-08]-An Invoice shall contain the Seller postal address (BG-5) ",
        check: Check::Structural(
            C::Root,
            R::Exists(&[a("AccountingSupplierParty"), a("Party"), a("PostalAddress")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:041:BR-KSA-F-06-C27",
        code: "BR-KSA-F-06-C27",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C27] - Field character limits for the Buyer Address - Province/State field (BT-54) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::Structural(
            C::Root,
            R::Length(
                &[
                    a("AccountingCustomerParty"),
                    a("Party"),
                    a("PostalAddress"),
                    b("CountrySubentity"),
                ],
                0,
                127,
            ),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:042:BR-16",
        code: "BR-16",
        severity: Severity::Error,
        message: "[BR-16]-An Invoice shall have at least one Invoice line (BG-25)",
        check: Check::Structural(C::Root, R::InvoiceLines),
    },
    Rule {
        source: Source::Cen,
        site: "cen:043:BR-53",
        code: "BR-53",
        severity: Severity::Warning,
        message: "[BR-53]-If the VAT accounting currency code (BT-6) is present, then the Invoice total VAT amount in accounting currency (BT-111) shall be provided.",
        check: Check::Structural(C::Root, R::TaxAccounting),
    },
    Rule {
        source: Source::Cen,
        site: "cen:044:BR-KSA-F-06-C17",
        code: "BR-KSA-F-06-C17",
        severity: Severity::Error,
        message: "[BR-KSA-F-06-C17] - Field character limits for Invoice line identifier field (BT-126) have not been met. The minimum limit is 1 character and the maximum limit is 6 characters.",
        check: Check::Structural(C::All(&[a("InvoiceLine")]), R::Length(&[b("ID")], 1, 6)),
    },
    Rule {
        source: Source::Cen,
        site: "cen:045:BR-KSA-F-06-C30",
        code: "BR-KSA-F-06-C30",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C30] - Field character limits for Item Buyer's identifier field (BT-156) have not been met. The maximum limit is 127 characters.",
        check: Check::Structural(
            C::All(&[a("InvoiceLine")]),
            R::Length(&[a("Item"), a("BuyersItemIdentification"), b("ID")], 0, 127),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:046:BR-KSA-F-06-C31",
        code: "BR-KSA-F-06-C31",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C31] - Field character limits for Item Seller's identifier field (BT-155) have not been met. The maximum limit is 127 characters.",
        check: Check::Structural(
            C::All(&[a("InvoiceLine")]),
            R::Length(
                &[a("Item"), a("SellersItemIdentification"), b("ID")],
                0,
                127,
            ),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:047:BR-KSA-F-06-C20",
        code: "BR-KSA-F-06-C20",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C20] - Field character limits for Item standard identifier field (BT-157) have not been met. The maximum limit is 127 characters.",
        check: Check::Structural(
            C::All(&[a("InvoiceLine")]),
            R::Length(
                &[a("Item"), a("StandardItemIdentification"), b("ID")],
                0,
                127,
            ),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:048:BR-CO-15",
        code: "BR-CO-15",
        severity: Severity::Error,
        message: "[BR-CO-15]-Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).",
        check: Check::InclusiveTotal,
    },
    Rule {
        source: Source::Cen,
        site: "cen:049:BR-CO-18",
        code: "BR-CO-18",
        severity: Severity::Error,
        message: "[BR-CO-18]-An Invoice shall at least have one VAT breakdown group (BG-23).",
        check: Check::Structural(C::Root, R::Exists(&[a("TaxTotal"), a("TaxSubtotal")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:056:BR-KSA-F-06-C18",
        code: "BR-KSA-F-06-C18",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C18] - Field character limits for Invoiced quantity unit of measure field (BT-130) have not been met. The maximum limit is 127 characters.",
        check: Check::Structural(
            C::Lines,
            R::AttributeLength(&[b("InvoicedQuantity")], "unitCode", 127),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:057:BR-KSA-F-06-C19",
        code: "BR-KSA-F-06-C19",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C19] - Field character limits for Item name field (BT-153) have not been met. The minimum limit is 3 character and the maximum limit is 1000 characters.",
        check: Check::Structural(C::Lines, R::Length(&[a("Item"), b("Name")], 3, 1000)),
    },
    Rule {
        source: Source::Cen,
        site: "cen:058:BR-KSA-F-C-01",
        code: "BR-KSA-F-C-01",
        severity: Severity::Warning,
        message: "[BR-KSA-F-C-01] - Please recheck Item Description (BT-153). Providing unclear description violates the requirements specified in Article 53 of VAT Regulations.",
        check: Check::Structural(C::Lines, R::ItemName),
    },
    Rule {
        source: Source::Cen,
        site: "cen:059:BR-21",
        code: "BR-21",
        severity: Severity::Warning,
        message: "[BR-21]-Each Invoice line (BG-25) shall have an Invoice line identifier (BT-126).",
        check: Check::Structural(C::Lines, R::Nonempty(&[b("ID")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:060:BR-22",
        code: "BR-22",
        severity: Severity::Error,
        message: "[BR-22]-Each Invoice line (BG-25) shall have an Invoiced quantity (BT-129).",
        check: Check::Structural(C::Lines, R::InvoicedQuantity),
    },
    Rule {
        source: Source::Cen,
        site: "cen:061:BR-24",
        code: "BR-24",
        severity: Severity::Error,
        message: "[BR-24]-Each Invoice line (BG-25) shall have an Invoice line net amount (BT-131).",
        check: Check::Structural(C::Lines, R::Exists(&[b("LineExtensionAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:062:BR-25",
        code: "BR-25",
        severity: Severity::Warning,
        message: "[BR-25]-Each Invoice line (BG-25) shall contain the Item name (BT-153).",
        check: Check::ItemName,
    },
    Rule {
        source: Source::Cen,
        site: "cen:063:BR-26",
        code: "BR-26",
        severity: Severity::Error,
        message: "[BR-26]-Each Invoice line (BG-25) shall contain the Item net price (BT-146).",
        check: Check::Structural(C::Lines, R::Exists(&[a("Price"), b("PriceAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:064:BR-CO-04",
        code: "BR-CO-04",
        severity: Severity::Error,
        message: "[BR-CO-04]-Each Invoice line (BG-25) shall be categorized with an Invoiced item VAT category code (BT-151).",
        check: Check::Structural(C::Lines, R::ItemVatCategory),
    },
    Rule {
        source: Source::Cen,
        site: "cen:065:BR-DEC-23",
        code: "BR-DEC-23",
        severity: Severity::Warning,
        message: "[BR-DEC-23]-The allowed maximum number of decimals for the Invoice line net amount (BT-131) is 2.",
        check: Check::Structural(C::Lines, R::Scale(&[b("LineExtensionAmount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:066:BR-41",
        code: "BR-41",
        severity: Severity::Error,
        message: "[BR-41]-Each Invoice line allowance (BG-27) shall have an Invoice line allowance amount (BT-136).",
        check: Check::Structural(C::LineAllowance, R::Exists(&[b("Amount")])),
    },
    Rule {
        source: Source::Cen,
        site: "cen:067:BR-DEC-24",
        code: "BR-DEC-24",
        severity: Severity::Warning,
        message: "[BR-DEC-24]-The allowed maximum number of decimals for the Invoice line allowance amount (BT-136) is 2.",
        check: Check::LineAllowanceScale("Amount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:068:BR-DEC-25",
        code: "BR-DEC-25",
        severity: Severity::Warning,
        message: "[BR-DEC-25]-The allowed maximum number of decimals for the Invoice line allowance base amount (BT-137) is 2.",
        check: Check::LineAllowanceScale("BaseAmount"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:069:BR-54",
        code: "BR-54",
        severity: Severity::Error,
        message: "[BR-54]-Each Item attribute (BG-32) shall contain an Item attribute name (BT-160) and an Item attribute value (BT-161).",
        check: Check::Structural(C::All(&[a("AdditionalItemProperty")]), R::ItemProperty),
    },
    Rule {
        source: Source::Cen,
        site: "cen:070:BR-49",
        code: "BR-49",
        severity: Severity::Warning,
        message: "[BR-49]-A Payment instruction (BG-16) shall specify the Payment means type code (BT-81).",
        check: Check::Structural(C::All(&[a("PaymentMeans")]), R::PaymentCode),
    },
    Rule {
        source: Source::Cen,
        site: "cen:071:BR-55",
        code: "BR-55",
        severity: Severity::Error,
        message: "[BR-55]-Each Preceding Invoice reference (BG-3) shall contain a Preceding Invoice reference (BT-25).",
        check: Check::Structural(
            C::All(&[a("BillingReference")]),
            R::Nonempty(&[a("InvoiceDocumentReference"), b("ID")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:072:BR-09",
        code: "BR-09",
        severity: Severity::Warning,
        message: "[BR-09]-The Seller postal address (BG-5) shall contain a Seller country code (BT-40).",
        check: Check::Structural(
            C::All(&[a("AccountingSupplierParty"), a("Party"), a("PostalAddress")]),
            R::Nonempty(&[a("Country"), b("IdentificationCode")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:073:BR-CO-14",
        code: "BR-CO-14",
        severity: Severity::Error,
        message: "[BR-CO-14]-Invoice total VAT amount (BT-110) = Σ VAT category tax amount (BT-117).",
        check: Check::TaxSum,
    },
    Rule {
        source: Source::Cen,
        site: "cen:074:BR-45",
        code: "BR-45",
        severity: Severity::Error,
        message: "[BR-45]-Each VAT breakdown (BG-23) shall have a VAT category taxable amount (BT-116).",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::Exists(&[b("TaxableAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:075:BR-46",
        code: "BR-46",
        severity: Severity::Error,
        message: "[BR-46]-Each VAT breakdown (BG-23) shall have a VAT category tax amount (BT-117).",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::Exists(&[b("TaxAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:076:BR-47",
        code: "BR-47",
        severity: Severity::Error,
        message: "[BR-47]-Each VAT breakdown (BG-23) shall be defined through a VAT category code (BT-118).",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::VatCategory(&[a("TaxCategory")], false),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:077:BR-48",
        code: "BR-48",
        severity: Severity::Error,
        message: "[BR-48]-Each VAT breakdown (BG-23) shall have a VAT category rate (BT-119), except if the Invoice is not subject to VAT.",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::VatRate,
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:079:BR-DEC-19",
        code: "BR-DEC-19",
        severity: Severity::Warning,
        message: "[BR-DEC-19]-The allowed maximum number of decimals for the VAT category taxable amount (BT-116) is 2.",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::Scale(&[b("TaxableAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:080:BR-DEC-20",
        code: "BR-DEC-20",
        severity: Severity::Warning,
        message: "[BR-DEC-20]-The allowed maximum number of decimals for the VAT category tax amount (BT-117) is 2.",
        check: Check::Structural(
            C::InvoicePath(&[a("TaxTotal"), a("TaxSubtotal")]),
            R::Scale(&[b("TaxAmount")]),
        ),
    },
    Rule {
        source: Source::Cen,
        site: "cen:096:BR-DEC-13",
        code: "BR-DEC-13",
        severity: Severity::Warning,
        message: "[BR-DEC-13]-The allowed maximum number of decimals for the Invoice total VAT amount (BT-110) is 2.",
        check: Check::TaxScale("DocumentCurrencyCode"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:097:BR-DEC-15",
        code: "BR-DEC-15",
        severity: Severity::Warning,
        message: "[BR-DEC-15]-The allowed maximum number of decimals for the Invoice total VAT amount in accounting currency (BT-111) is 2.",
        check: Check::TaxScale("TaxCurrencyCode"),
    },
    Rule {
        source: Source::Cen,
        site: "cen:098:BR-CL-01",
        code: "BR-CL-01",
        severity: Severity::Error,
        message: "[BR-CL-01]-The document type code MUST be coded by the invoice and credit note related code lists of UNTDID 1001.",
        check: Check::CodeList(CodeListCheck::DocumentType),
    },
    Rule {
        source: Source::Cen,
        site: "cen:099:BR-CL-03",
        code: "BR-CL-03",
        severity: Severity::Error,
        message: "[BR-CL-03]-currencyID MUST be coded using ISO code list 4217 alpha-3",
        check: Check::CodeList(CodeListCheck::AmountCurrency),
    },
    Rule {
        source: Source::Cen,
        site: "cen:100:BR-CL-04",
        code: "BR-CL-04",
        severity: Severity::Error,
        message: "[BR-CL-04]-Invoice currency code MUST be coded using ISO code list 4217 alpha-3",
        check: Check::CodeList(CodeListCheck::DocumentCurrency),
    },
    Rule {
        source: Source::Cen,
        site: "cen:101:BR-CL-05",
        code: "BR-CL-05",
        severity: Severity::Error,
        message: "[BR-CL-05]-Tax currency code MUST be coded using ISO code list 4217 alpha-3",
        check: Check::CodeList(CodeListCheck::TaxCurrency),
    },
    Rule {
        source: Source::Cen,
        site: "cen:102:BR-CL-14",
        code: "BR-CL-14",
        severity: Severity::Warning,
        message: "[BR-CL-14]-Country codes in an invoice MUST be coded using ISO code list 3166-1",
        check: Check::CodeList(CodeListCheck::Country),
    },
    Rule {
        source: Source::Cen,
        site: "cen:103:BR-CL-16",
        code: "BR-CL-16",
        severity: Severity::Warning,
        message: "[BR-CL-16]-Payment means in an invoice MUST be coded using UNCL4461 code list",
        check: Check::CodeList(CodeListCheck::PaymentMeans),
    },
    Rule {
        source: Source::Cen,
        site: "cen:104:BR-CL-18",
        code: "BR-CL-18",
        severity: Severity::Error,
        message: "[BR-CL-18]-Invoice tax categories MUST be coded using UNCL5305 code list.",
        check: Check::CodeList(CodeListCheck::TaxCategory),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:034:BR-KSA-05",
        code: "BR-KSA-05",
        severity: Severity::Error,
        message: "[BR-KSA-05]-The invoice type code (BT-3) must be equal to one of value from the subset of UN/CEFACT code list 1001, D.16B agreed for KSA electronic invoices. Please refer paragraph 11.2.1 of XML implementation Standards.",
        check: Check::KsaField(KsaFieldCheck::InvoiceType),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:035:BR-KSA-06",
        code: "BR-KSA-06",
        severity: Severity::Error,
        message: "[BR-KSA-06]-The invoice transaction code (KSA-2) must exist and respect the following structure:\n                        NNPNESBCG\n                        where\n                        NN (positions 1 and 2) = invoice subtype:\n                        - 01 for tax invoice\n                        - 02 for simplified tax invoice\n                        P (position 3) = 3rd Party invoice transaction, 0 for false, 1 for true;\n                        N (position 4) = Nominal invoice transaction, 0 for false, 1 for true;\n                        E (position 5) = Exports invoice transaction, 0 for false, 1 for true;\n                        S (position 6) = Summary invoice transaction, 0 for false, 1 for true;\n                        B (position 7) = Self billed invoice transaction, 0 for false, 1 for true;\n                        C (position 8) = Continuous Supply invoice transaction, 0 for false, 1 for true;\n                        G (position 9) = B2G invoice transaction, 0 for false, 1 for true\n                     ",
        check: Check::KsaField(KsaFieldCheck::TransactionCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:036:BR-KSA-F-06-C40",
        code: "BR-KSA-F-06-C40",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C40]-Field character limits for Invoice transaction code (KSA-2) have not been met. The minimum limit is 7 characters and the maximum limit is 9 characters.",
        check: Check::KsaField(KsaFieldCheck::TransactionLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:037:BR-KSA-F-08",
        code: "BR-KSA-F-08",
        severity: Severity::Warning,
        message: "[BR-KSA-F-08] - The value provided in Other Seller ID (BT-29) or Other Buyer ID (BT-46) for the scheme ID 'CRN' appears to be\n                  incorrect. Please recheck the value to avoid non-compliance.\n               ",
        check: Check::Identity(IdentityCheck::Crn),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:038:BR-KSA-F-09",
        code: "BR-KSA-F-09",
        severity: Severity::Warning,
        message: "[BR-KSA-F-09] - The value provided in Other Seller ID (BT-29) or Other Buyer ID (BT-46) for the scheme ID '700' appears to be incorrect. Please recheck the value to avoid non-compliance.",
        check: Check::Identity(IdentityCheck::UnifiedId),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:039:BR-KSA-F-12",
        code: "BR-KSA-F-12",
        severity: Severity::Warning,
        message: "\n                  [BR-KSA-F-12] - The Other Seller/Buyer schema ID (BT-29-1 or BT-46-1) contains spaces. Please recheck the attribute and remove the empty space to avoid non-compliance.\n               ",
        check: Check::Identity(IdentityCheck::SchemeWhitespace),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:040:BR-KSA-F-13",
        code: "BR-KSA-F-13",
        severity: Severity::Warning,
        message: "\n                  [BR-KSA-F-13] - Please recheck Other Seller/Buyer ID (BT-29 or BT-46) as it contains an invalid value.\n               ",
        check: Check::Identity(IdentityCheck::PredictableId),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:041:BR-KSA-14",
        code: "BR-KSA-14",
        severity: Severity::Error,
        message: "[BR-KSA-14]-The buyer identification (BT-46), required only if buyer is not VAT registered, then the buyer identification (BT-46) must be provided with one of the scheme IDs (BT-46-1) (TIN, CRN, MOM, MLS, 700, SAG, NAT, GCC, IQA, PAS, OTH) and must contain only alphanumeric characters. Tax Identification Number \"TIN\" as schemeID ;Commercial registration number with \"CRN\" as schemeID ;MOMRAH license with \"MOM\" as schemeID ;MHRSD license with \"MLS\" as schemeID ;700 Number with \"700\" as schemeID ;MISA license with \"SAG\" as schemeID ;National ID with \"NAT\" as schemeID ;GCC ID with \"GCC\" as schemeID ;Iqama Number with \"IQA\" as schemeID ;Passport ID with \"PAS\" as schemeID ;Other ID with \"OTH\" as schemeID. ;In case of multiple commercial registrations, the seller should fill the commercial registration of the branch in respect of which the Tax Invoice is being issued. In case multiple IDs exist then one of the above must be entered following the sequence specified above",
        check: Check::Identity(IdentityCheck::BuyerScheme),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:042:BR-KSA-F-07",
        code: "BR-KSA-F-07",
        severity: Severity::Warning,
        message: "[BR-KSA-F-07] - The value provided in Other Buyer ID (BT-46) for scheme ID 'TIN' appears to be incorrect. Please recheck the value to avoid non-compliance.\n                     ",
        check: Check::Identity(IdentityCheck::BuyerTin),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:043:BR-KSA-F-10",
        code: "BR-KSA-F-10",
        severity: Severity::Warning,
        message: "[BR-KSA-F-10] - The value provided in Other Buyer ID (BT-46) for the scheme ID 'NAT' appears to be incorrect. Please recheck the value to avoid non-compliance.",
        check: Check::Identity(IdentityCheck::BuyerNationalId),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:044:BR-KSA-F-11",
        code: "BR-KSA-F-11",
        severity: Severity::Warning,
        message: "[BR-KSA-F-11] - The value provided in Other Buyer ID (BT-46) for the scheme ID 'IQA' appears to be incorrect. Please recheck the value to avoid non-compliance. ",
        check: Check::Identity(IdentityCheck::BuyerResidenceId),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:045:BR-KSA-F-06-C4",
        code: "BR-KSA-F-06-C4",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C4] - Field character limits for the Seller Address - Street field (BT-35) have not been met. The minimum limit is 1 character and the maximum limit is 1000 characters.",
        check: Check::Identity(IdentityCheck::SellerStreet),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:046:BR-KSA-09",
        code: "BR-KSA-09",
        severity: Severity::Warning,
        message: "[BR-KSA-09]-Seller address must contain street name (BT-35), building number (KSA-17), postal code (BT-38), city (BT-37), district (KSA-3), country code (BT-40). For more information please access this link: https://splonline.com.sa/en/national-address-1/",
        check: Check::Identity(IdentityCheck::SellerAddress),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:047:BR-KSA-F-06-C11",
        code: "BR-KSA-F-06-C11",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C11] - Field character limits for the Buyer Address - Additional street field (BT-51) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::Identity(IdentityCheck::BuyerAdditionalStreet),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:048:BR-KSA-F-06-C7",
        code: "BR-KSA-F-06-C7",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C7] - Field character limits for the Seller Address - City field (BT-37) have not been met. The minimum limit is 1 character and the maximum limit is 127 characters.\n                     ",
        check: Check::Identity(IdentityCheck::SellerCity),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:049:BR-KSA-F-06-C6",
        code: "BR-KSA-F-06-C6",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C6] - Field character limits for the Seller Address - Additional street field (BT-36) have not been met. The maximum limit is 127 characters.",
        check: Check::Identity(IdentityCheck::SellerAdditionalStreet),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:050:BR-KSA-66",
        code: "BR-KSA-66",
        severity: Severity::Warning,
        message: "[BR-KSA-66]-Seller postal code (BT-38) must be 5 digits.",
        check: Check::Identity(IdentityCheck::SellerPostcode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:057:BR-KSA-37",
        code: "BR-KSA-37",
        severity: Severity::Warning,
        message: "[BR-KSA-37]-The seller address building number must contain 4 digits.",
        check: Check::Identity(IdentityCheck::SellerBuilding),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:058:BR-KSA-40",
        code: "BR-KSA-40",
        severity: Severity::Error,
        message: "[BR-KSA-40]-If it exists in the invoice, the seller VAT registration number (BT-31) must contain 15 digits. The first and the last digits are \"3\"..",
        check: Check::Identity(IdentityCheck::SellerVat),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:063:BR-KSA-63",
        code: "BR-KSA-63",
        severity: Severity::Warning,
        message: "[BR-KSA-63]-If the buyer country code (BT-55) is \"SA\", then these fields are mandatory:street name (BT-50), building number (KSA-18), postal code (BT-53), city (BT-52), District (KSA-4), country code (BT-55).For more information please access this link:https://splonline.com.sa/en/national-address-1/",
        check: Check::KsaBuyer(KsaBuyerCheck::SaAddress),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:064:BR-KSA-F-06-C28",
        code: "BR-KSA-F-06-C28",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C28] - Field character limits for the Buyer Address - District field (KSA-4) have not been met. The minimum limit is 1 character  and the maximum limit is 127 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::DistrictRequired),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:065:BR-KSA-F-06-C29",
        code: "BR-KSA-F-06-C29",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C29] - Field character limits for the Buyer Address - District field (KSA-4) have not been met. The maximum limit is 127 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::DistrictLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:066:BR-KSA-F-06-C9",
        code: "BR-KSA-F-06-C9",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C9] - Field character limits for the Seller Address - District field (KSA-3) have not been met. The minimum limit is 1 character and the maximum limit is 127 characters.\n                     ",
        check: Check::KsaBuyer(KsaBuyerCheck::SellerDistrict),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:067:BR-KSA-67",
        code: "BR-KSA-67",
        severity: Severity::Warning,
        message: "[BR-KSA-67]-If the buyer country code (BT-55) is \"SA\", then the Buyer postal code(BT-53) must be 5 digits.",
        check: Check::KsaBuyer(KsaBuyerCheck::Postcode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:068:BR-KSA-72",
        code: "BR-KSA-72",
        severity: Severity::Error,
        message: "If the Invoice is a simplified invoice type and is a summary invoice (KSA-2, position 1 and 2 = 02, position 6 = 1), then a supply date (KSA-5) and supply end date (KSA-24) must be present\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::SummaryDates),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:069:BR-KSA-52",
        code: "BR-KSA-52",
        severity: Severity::Error,
        message: "[BR-KSA-52]-The line VAT amount (KSA-11) is mandatory for tax invoice and associated credit notes and debit notes (KSA-2, position 1 and 2 = 01).",
        check: Check::KsaBuyer(KsaBuyerCheck::LineTax),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:070:BR-KSA-F-06-C23",
        code: "BR-KSA-F-06-C23",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C23] - Field character limits for the Buyer Address - Street field (BT-50) have not been met. The minimum limit is 1 character and the maximum limit is 1000 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::StreetRequired),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:071:BR-KSA-F-06-C25",
        code: "BR-KSA-F-06-C25",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C25] - Field character limits for the Buyer Address - City field (BT-52) have not been met. The minimum limit is 1 character and the maximum limit is 127 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::CityRequired),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:072:BR-KSA-F-06-C32",
        code: "BR-KSA-F-06-C32",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C32] - Field character limits for Buyer name field (BT-44) have not been met. The maximum limit is 1000 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::SimpleNameLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:073:BR-KSA-F-06-C12",
        code: "BR-KSA-F-06-C12",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C12] - Field character limits for Buyer name field (BT-44) have not been met. The minimum limit is 1 character and the maximum limit is 1000 characters.\n                     ",
        check: Check::KsaBuyer(KsaBuyerCheck::StandardNameLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:074:BR-KSA-53",
        code: "BR-KSA-53",
        severity: Severity::Error,
        message: "[BR-KSA-53]-The line amount with VAT (KSA-12) is mandatory for tax invoice and associated credit notes and debit notes (KSA-2, position 1 and 2 = 01).",
        check: Check::KsaBuyer(KsaBuyerCheck::LineInclusive),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:075:BR-KSA-F-06-C14",
        code: "BR-KSA-F-06-C14",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C14]Field character limits for Payment terms field (KSA-22) have not been met. The maximum limit is 1000 characters.",
        check: Check::KsaBuyer(KsaBuyerCheck::PaymentNoteLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:076:BR-KSA-F-06-C24",
        code: "BR-KSA-F-06-C24",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C24] - Field character limits for the Buyer Address - Street field (BT-50) have not been met. The maximum limit is 1000 characters.\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::SimpleStreetLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:077:BR-KSA-F-06-C26",
        code: "BR-KSA-F-06-C26",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C26] - Field character limits for the Buyer Address - City field (BT-52) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::KsaBuyer(KsaBuyerCheck::CityLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:078:BR-KSA-16",
        code: "BR-KSA-16",
        severity: Severity::Warning,
        message: "[BR-KSA-16]-Payment means code (BT-81) in an invoice exist, then it must contain one of the values from subset of UNTDID 4461 code list",
        check: Check::KsaBuyer(KsaBuyerCheck::PaymentCode),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:079:BR-KSA-10",
        code: "BR-KSA-10",
        severity: Severity::Warning,
        message: "[BR-KSA-10]-Where the Buyer Country Code (BT-55) is other than 'SA' Buyer address must contain a street (BT-50), city (BT-52), country code (BT-55). This rule does not apply on the simplified tax invoices and associated credit notes and debit notes (KSA-2, position 1 and 2 = 02).",
        check: Check::KsaBuyer(KsaBuyerCheck::BuyerAddress),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:080:BR-KSA-F-06-C15",
        code: "BR-KSA-F-06-C15",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C15] - Field character limits for Payment account identifier field (BT-84) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::KsaBuyer(KsaBuyerCheck::AccountLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:081:BR-KSA-15",
        code: "BR-KSA-15",
        severity: Severity::Warning,
        message: "[BR-KSA-15]-The tax invoice  ((invoice type code (BT-30) = 388) and (invoice transaction code (KSA-2) has \"01\" as first 2 digits)) must contain the supply date (KSA-5).",
        check: Check::KsaBuyer(KsaBuyerCheck::SupplyDate),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:082:BR-KSA-17",
        code: "BR-KSA-17",
        severity: Severity::Error,
        message: "[BR-KSA-17]-Debit and credit note (invoice type code (BT-3) is equal to 383 or 381) must contain the reason (KSA-10) for this invoice type issuing.",
        check: Check::KsaBuyer(KsaBuyerCheck::NoteReason),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:083:BR-KSA-17",
        code: "BR-KSA-17",
        severity: Severity::Error,
        message: "[BR-KSA-17]-Debit and credit note (invoice type code (BT-3) is equal to 383 or 381) must contain the reason (KSA-10) for this invoice type issuing.",
        check: Check::KsaBuyer(KsaBuyerCheck::MissingPayment),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:084:BR-KSA-F-06-C13",
        code: "BR-KSA-F-06-C13",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C13] - Field character limits for Reasons for issuance of credit / debit note field (KSA-10) have not been met. The minimum limit is 1 character and the maximum limit is 1000 characters .\n                        ",
        check: Check::KsaBuyer(KsaBuyerCheck::NoteReasonLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:085:BR-KSA-56",
        code: "BR-KSA-56",
        severity: Severity::Warning,
        message: "[BR-KSA-56]-For credit notes ((BT-3) has the value of 381) and debit notes ((BT-3) has the value of 383), the billing reference ID (BT-25) is  mandatory.",
        check: Check::KsaBuyer(KsaBuyerCheck::NoteReference),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:086:BR-KSA-F-06-C22",
        code: "BR-KSA-F-06-C22",
        severity: Severity::Error,
        message: "[BR-KSA-F-06-C22]-Field character limits for Billing reference ID field (BT-25) have not been met. The minimum limit is 1 character and the maximum limit is 5000 characters.",
        check: Check::KsaBuyer(KsaBuyerCheck::NoteReferenceLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:087:BR-KSA-56",
        code: "BR-KSA-56",
        severity: Severity::Warning,
        message: "[BR-KSA-56]-For credit notes ((BT-3) has the value of 381) and debit notes ((BT-3) has the value of 383), the billing reference ID (BT-25) is  mandatory.",
        check: Check::KsaBuyer(KsaBuyerCheck::MissingReference),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:088:BR-KSA-25",
        code: "BR-KSA-25",
        severity: Severity::Warning,
        message: "[BR-KSA-25]-If it is a simplified tax invoice or an associated credit note or a debit note (KSA-2, position 1 and 2 = 02) and the tax exemption reason code (BT-121) is equal with VATEX-SA-EDU or VATEX-SA-HEA, then buyer name (BT-44) is mandatory.",
        check: Check::KsaBuyer(KsaBuyerCheck::SimpleBuyer),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:089:BR-KSA-31",
        code: "BR-KSA-31",
        severity: Severity::Error,
        message: "\n                        [BR-KSA-31]- For Simplified Tax Invoices and associated credit notes and debit notes (KSA-2, position 1 and 2 = 02), transaction types \"self-billing\" (KSA-2, position 7 = True) is not allowed.",
        check: Check::KsaBuyer(KsaBuyerCheck::SimpleFlags),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:090:BR-KSA-60",
        code: "BR-KSA-60",
        severity: Severity::Warning,
        message: "[BR-KSA-60]-Cryptographic stamp (KSA-15) must exist in simplified tax invoices and associated credit notes and debit notes (KSA-2, position 1 and 2 = 02).",
        check: Check::KsaBuyer(KsaBuyerCheck::Stamp),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:091:BR-KSA-71",
        code: "BR-KSA-71",
        severity: Severity::Warning,
        message: "If the Invoice is a simplified invoice type and is a summary invoice (KSA-2, position 1 and 2 = 02, position 6 = 1),then the buyer name must be present.",
        check: Check::KsaBuyer(KsaBuyerCheck::SummaryBuyer),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:092:BR-KSA-07",
        code: "BR-KSA-07",
        severity: Severity::Error,
        message: "[BR-KSA-07]-Self billing is not allowed (KSA-2, position 7 cannot be \"1\") for export invoices (KSA-2, position 5 = 1).",
        check: Check::KsaBuyer(KsaBuyerCheck::ExportSelfBilling),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:093:BR-KSA-99",
        code: "BR-KSA-99",
        severity: Severity::Warning,
        message: "If it exists in the invoice,  the buyer VAT registration number or buyer group VAT registration number (BT-48) should not be left empty in the tax invoice and associated credit notes and debit notes (KSA-2, position 1 and 2 = 01).",
        check: Check::KsaBuyer(KsaBuyerCheck::EmptyBuyerVat),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:094:BR-KSA-44",
        code: "BR-KSA-44",
        severity: Severity::Error,
        message: "[BR-KSA-44]-If it exists in the invoice,the buyer VAT registration number or buyer group VAT registration number (BT-48) must contain 15 digits. The first digit and the last digit is \"3\".",
        check: Check::Identity(IdentityCheck::BuyerVat),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:133:BR-KSA-EN16931-01",
        code: "BR-KSA-EN16931-01",
        severity: Severity::Error,
        message: "[BR-KSA-EN16931-01]-Business process (BT-23) must be \"reporting:1.0\".",
        check: Check::KsaField(KsaFieldCheck::Profile),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:134:BR-KSA-EN16931-08",
        code: "BR-KSA-EN16931-08",
        severity: Severity::Warning,
        message: "[BR-KSA-EN16931-08]-Only one tax total (BG-22) with tax subtotals must be provided.Refer to Calculation of VAT.",
        check: Check::KsaField(KsaFieldCheck::TaxSubtotalTotal),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:136:BR-KSA-EN16931-02",
        code: "BR-KSA-EN16931-02",
        severity: Severity::Error,
        message: "[BR-KSA-EN16931-02]-VAT accounting currency code (BT-6) must be \"SAR\".",
        check: Check::TaxCurrency,
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:137:BR-KSA-EN16931-09",
        code: "BR-KSA-EN16931-09",
        severity: Severity::Warning,
        message: "[BR-KSA-EN16931-09]-Only one tax total (BG-22) without tax subtotals (BG-23) must be provided when tax currency code is provided .",
        check: Check::BareTaxTotal,
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:139:BR-KSA-EN16931-05",
        code: "BR-KSA-EN16931-05",
        severity: Severity::Warning,
        message: "[BR-KSA-EN16931-05]-Allowance/Charge percentage (BT-94, BT-101, BT-138, BT-143) must be provided when the allowance/Charge base amount (BT-93, BT-100, BT-137, BT-142) is provided.",
        check: Check::KsaField(KsaFieldCheck::BasePercentage),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:140:BR-KSA-EN16931-04",
        code: "BR-KSA-EN16931-04",
        severity: Severity::Warning,
        message: "[BR-KSA-EN16931-04]-Allowance/Charge base amount (BT-93, BT-100, BT-137, BT-142) must be provided when allowance/Charge percentage (BT-94, BT-101,BT-138, BT-143) is provided.",
        check: Check::KsaField(KsaFieldCheck::PercentageBase),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:141:BR-KSA-EN16931-06",
        code: "BR-KSA-EN16931-06",
        severity: Severity::Error,
        message: "[BR-KSA-EN16931-06]-Charge on price level (BG-29) is not allowed. The value of Indicator should be 'false'.",
        check: Check::KsaField(KsaFieldCheck::NoPriceCharge),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:143:BR-KSA-F-06-C21",
        code: "BR-KSA-F-06-C21",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C21] - Field character limits for Item price base quantity unit code field (BT-150) have not been met. The maximum limit is 127 characters.\n                     ",
        check: Check::KsaField(KsaFieldCheck::BaseUnitLength),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:144:BR-KSA-EN16931-12",
        code: "BR-KSA-EN16931-12",
        severity: Severity::Error,
        message: "[BR-KSA-EN16931-12]-Base quantity (BT-149) must be a positive number above zero.",
        check: Check::KsaField(KsaFieldCheck::PositiveBaseQuantity),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:146:BR-KSA-85",
        code: "BR-KSA-85",
        severity: Severity::Warning,
        message: "[BR-KSA-85]-The Buyer's contact phone number (BT-57) shall start with \"0\" or \"+\", followed by a maximum of 15 number and minimum 4 character after the \"+\" or \"0\" , if exist.",
        check: Check::Identity(IdentityCheck::BuyerPhone),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:147:BR-KSA-F-06-C37",
        code: "BR-KSA-F-06-C37",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C37] - Field character limits for the contact name - Buyer's contact point field (BT-56) have not been met. The maximum limit is 1000 characters.\n                     ",
        check: Check::Identity(IdentityCheck::ContactName),
    },
    Rule {
        source: Source::Ksa,
        site: "ksa:148:BR-KSA-F-06-C38",
        code: "BR-KSA-F-06-C38",
        severity: Severity::Warning,
        message: "[BR-KSA-F-06-C38] - Field character limits for the contact note - Buyer's Contact Note field (KSA-35) have not been met. The maximum limit is 1000 characters.\n                     ",
        check: Check::Identity(IdentityCheck::ContactNote),
    },
];
